/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.api;

import io.stripyhorse.ApiCallback;
import io.stripyhorse.ApiClient;
import io.stripyhorse.ApiException;
import io.stripyhorse.ApiResponse;
import io.stripyhorse.Configuration;
import io.stripyhorse.Pair;
import io.stripyhorse.ProgressRequestBody;
import io.stripyhorse.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.stripyhorse.model.ErrorModel;
import io.stripyhorse.model.HostStatusInputBody;
import io.stripyhorse.model.HostStatusOutputBody;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PrintersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PrintersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PrintersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for parseHostStatus
     * @param hostStatusInputBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call parseHostStatusCall(@javax.annotation.Nonnull HostStatusInputBody hostStatusInputBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = hostStatusInputBody;

        // create path and map variables
        String localVarPath = "/v1/host-status/parse";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "headerKey", "bearerKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call parseHostStatusValidateBeforeCall(@javax.annotation.Nonnull HostStatusInputBody hostStatusInputBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'hostStatusInputBody' is set
        if (hostStatusInputBody == null) {
            throw new ApiException("Missing the required parameter 'hostStatusInputBody' when calling parseHostStatus(Async)");
        }

        return parseHostStatusCall(hostStatusInputBody, _callback);

    }

    /**
     * Decode a Zebra ~HS host status response
     * Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
     * @param hostStatusInputBody  (required)
     * @return HostStatusOutputBody
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public HostStatusOutputBody parseHostStatus(@javax.annotation.Nonnull HostStatusInputBody hostStatusInputBody) throws ApiException {
        ApiResponse<HostStatusOutputBody> localVarResp = parseHostStatusWithHttpInfo(hostStatusInputBody);
        return localVarResp.getData();
    }

    /**
     * Decode a Zebra ~HS host status response
     * Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
     * @param hostStatusInputBody  (required)
     * @return ApiResponse&lt;HostStatusOutputBody&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<HostStatusOutputBody> parseHostStatusWithHttpInfo(@javax.annotation.Nonnull HostStatusInputBody hostStatusInputBody) throws ApiException {
        okhttp3.Call localVarCall = parseHostStatusValidateBeforeCall(hostStatusInputBody, null);
        Type localVarReturnType = new TypeToken<HostStatusOutputBody>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Decode a Zebra ~HS host status response (asynchronously)
     * Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
     * @param hostStatusInputBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call parseHostStatusAsync(@javax.annotation.Nonnull HostStatusInputBody hostStatusInputBody, final ApiCallback<HostStatusOutputBody> _callback) throws ApiException {

        okhttp3.Call localVarCall = parseHostStatusValidateBeforeCall(hostStatusInputBody, _callback);
        Type localVarReturnType = new TypeToken<HostStatusOutputBody>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
