/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.api;

import io.stripyhorse.ApiCallback;
import io.stripyhorse.ApiClient;
import io.stripyhorse.ApiException;
import io.stripyhorse.ApiResponse;
import io.stripyhorse.Configuration;
import io.stripyhorse.Pair;
import io.stripyhorse.ProgressRequestBody;
import io.stripyhorse.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.stripyhorse.model.ErrorModel;
import io.stripyhorse.model.PreflightInputBody;
import io.stripyhorse.model.PreflightOutputBody;
import io.stripyhorse.model.RenderInputBody;
import io.stripyhorse.model.RenderOutputBody;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RenderApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public RenderApi() {
        this(Configuration.getDefaultApiClient());
    }

    public RenderApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for preflightLabel
     * @param preflightInputBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call preflightLabelCall(@javax.annotation.Nonnull PreflightInputBody preflightInputBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = preflightInputBody;

        // create path and map variables
        String localVarPath = "/v1/preflight";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "headerKey", "bearerKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call preflightLabelValidateBeforeCall(@javax.annotation.Nonnull PreflightInputBody preflightInputBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'preflightInputBody' is set
        if (preflightInputBody == null) {
            throw new ApiException("Missing the required parameter 'preflightInputBody' when calling preflightLabel(Async)");
        }

        return preflightLabelCall(preflightInputBody, _callback);

    }

    /**
     * Grade a label&#39;s barcodes before they ship
     * Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
     * @param preflightInputBody  (required)
     * @return PreflightOutputBody
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public PreflightOutputBody preflightLabel(@javax.annotation.Nonnull PreflightInputBody preflightInputBody) throws ApiException {
        ApiResponse<PreflightOutputBody> localVarResp = preflightLabelWithHttpInfo(preflightInputBody);
        return localVarResp.getData();
    }

    /**
     * Grade a label&#39;s barcodes before they ship
     * Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
     * @param preflightInputBody  (required)
     * @return ApiResponse&lt;PreflightOutputBody&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PreflightOutputBody> preflightLabelWithHttpInfo(@javax.annotation.Nonnull PreflightInputBody preflightInputBody) throws ApiException {
        okhttp3.Call localVarCall = preflightLabelValidateBeforeCall(preflightInputBody, null);
        Type localVarReturnType = new TypeToken<PreflightOutputBody>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Grade a label&#39;s barcodes before they ship (asynchronously)
     * Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
     * @param preflightInputBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call preflightLabelAsync(@javax.annotation.Nonnull PreflightInputBody preflightInputBody, final ApiCallback<PreflightOutputBody> _callback) throws ApiException {

        okhttp3.Call localVarCall = preflightLabelValidateBeforeCall(preflightInputBody, _callback);
        Type localVarReturnType = new TypeToken<PreflightOutputBody>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for renderZpl
     * @param renderInputBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renderZplCall(@javax.annotation.Nonnull RenderInputBody renderInputBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = renderInputBody;

        // create path and map variables
        String localVarPath = "/v1/render";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "headerKey", "bearerKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call renderZplValidateBeforeCall(@javax.annotation.Nonnull RenderInputBody renderInputBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'renderInputBody' is set
        if (renderInputBody == null) {
            throw new ApiException("Missing the required parameter 'renderInputBody' when calling renderZpl(Async)");
        }

        return renderZplCall(renderInputBody, _callback);

    }

    /**
     * Render ZPL to PNG images
     * Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
     * @param renderInputBody  (required)
     * @return RenderOutputBody
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public RenderOutputBody renderZpl(@javax.annotation.Nonnull RenderInputBody renderInputBody) throws ApiException {
        ApiResponse<RenderOutputBody> localVarResp = renderZplWithHttpInfo(renderInputBody);
        return localVarResp.getData();
    }

    /**
     * Render ZPL to PNG images
     * Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
     * @param renderInputBody  (required)
     * @return ApiResponse&lt;RenderOutputBody&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<RenderOutputBody> renderZplWithHttpInfo(@javax.annotation.Nonnull RenderInputBody renderInputBody) throws ApiException {
        okhttp3.Call localVarCall = renderZplValidateBeforeCall(renderInputBody, null);
        Type localVarReturnType = new TypeToken<RenderOutputBody>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Render ZPL to PNG images (asynchronously)
     * Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
     * @param renderInputBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renderZplAsync(@javax.annotation.Nonnull RenderInputBody renderInputBody, final ApiCallback<RenderOutputBody> _callback) throws ApiException {

        okhttp3.Call localVarCall = renderZplValidateBeforeCall(renderInputBody, _callback);
        Type localVarReturnType = new TypeToken<RenderOutputBody>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for renderZplPng
     * @param renderInputBody  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * Content-Type -  <br>  * X-Label-Count -  <br>  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renderZplPngCall(@javax.annotation.Nonnull RenderInputBody renderInputBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = renderInputBody;

        // create path and map variables
        String localVarPath = "/v1/render.png";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json",
            "application/problem+json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "headerKey", "bearerKey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call renderZplPngValidateBeforeCall(@javax.annotation.Nonnull RenderInputBody renderInputBody, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'renderInputBody' is set
        if (renderInputBody == null) {
            throw new ApiException("Missing the required parameter 'renderInputBody' when calling renderZplPng(Async)");
        }

        return renderZplPngCall(renderInputBody, _callback);

    }

    /**
     * Render ZPL and return the first label as a raw PNG
     * curl-friendly variant: the X-Label-Count response header carries the total label count.
     * @param renderInputBody  (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * Content-Type -  <br>  * X-Label-Count -  <br>  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public String renderZplPng(@javax.annotation.Nonnull RenderInputBody renderInputBody) throws ApiException {
        ApiResponse<String> localVarResp = renderZplPngWithHttpInfo(renderInputBody);
        return localVarResp.getData();
    }

    /**
     * Render ZPL and return the first label as a raw PNG
     * curl-friendly variant: the X-Label-Count response header carries the total label count.
     * @param renderInputBody  (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * Content-Type -  <br>  * X-Label-Count -  <br>  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<String> renderZplPngWithHttpInfo(@javax.annotation.Nonnull RenderInputBody renderInputBody) throws ApiException {
        okhttp3.Call localVarCall = renderZplPngValidateBeforeCall(renderInputBody, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Render ZPL and return the first label as a raw PNG (asynchronously)
     * curl-friendly variant: the X-Label-Count response header carries the total label count.
     * @param renderInputBody  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * Content-Type -  <br>  * X-Label-Count -  <br>  </td></tr>
        <tr><td> 0 </td><td> Error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call renderZplPngAsync(@javax.annotation.Nonnull RenderInputBody renderInputBody, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = renderZplPngValidateBeforeCall(renderInputBody, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
