/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.stripyhorse.model.Check;
import io.stripyhorse.model.DPIVerdict;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Barcode
 */
public class BarcodeTest {
    private final Barcode model = new Barcode();

    /**
     * Model tests for Barcode
     */
    @Test
    public void testBarcode() {
        // TODO: test Barcode
    }

    /**
     * Test the property 'blurMarginDots'
     */
    @Test
    public void blurMarginDotsTest() {
        // TODO: test blurMarginDots
    }

    /**
     * Test the property 'checks'
     */
    @Test
    public void checksTest() {
        // TODO: test checks
    }

    /**
     * Test the property 'crossDpi'
     */
    @Test
    public void crossDpiTest() {
        // TODO: test crossDpi
    }

    /**
     * Test the property 'format'
     */
    @Test
    public void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'moduleDots'
     */
    @Test
    public void moduleDotsTest() {
        // TODO: test moduleDots
    }

    /**
     * Test the property 'quietLeftModules'
     */
    @Test
    public void quietLeftModulesTest() {
        // TODO: test quietLeftModules
    }

    /**
     * Test the property 'quietRightModules'
     */
    @Test
    public void quietRightModulesTest() {
        // TODO: test quietRightModules
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'xDimensionMm'
     */
    @Test
    public void xDimensionMmTest() {
        // TODO: test xDimensionMm
    }

}
