/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.stripyhorse.model.Element;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ComposeInputBody
 */
public class ComposeInputBodyTest {
    private final ComposeInputBody model = new ComposeInputBody();

    /**
     * Model tests for ComposeInputBody
     */
    @Test
    public void testComposeInputBody() {
        // TODO: test ComposeInputBody
    }

    /**
     * Test the property 'dpmm'
     */
    @Test
    public void dpmmTest() {
        // TODO: test dpmm
    }

    /**
     * Test the property 'elements'
     */
    @Test
    public void elementsTest() {
        // TODO: test elements
    }

    /**
     * Test the property 'heightMm'
     */
    @Test
    public void heightMmTest() {
        // TODO: test heightMm
    }

    /**
     * Test the property 'preset'
     */
    @Test
    public void presetTest() {
        // TODO: test preset
    }

    /**
     * Test the property 'preview'
     */
    @Test
    public void previewTest() {
        // TODO: test preview
    }

    /**
     * Test the property 'variables'
     */
    @Test
    public void variablesTest() {
        // TODO: test variables
    }

    /**
     * Test the property 'widthMm'
     */
    @Test
    public void widthMmTest() {
        // TODO: test widthMm
    }

}
