/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePrinterInputBody
 */
public class CreatePrinterInputBodyTest {
    private final CreatePrinterInputBody model = new CreatePrinterInputBody();

    /**
     * Model tests for CreatePrinterInputBody
     */
    @Test
    public void testCreatePrinterInputBody() {
        // TODO: test CreatePrinterInputBody
    }

    /**
     * Test the property 'accessMode'
     */
    @Test
    public void accessModeTest() {
        // TODO: test accessMode
    }

    /**
     * Test the property 'anonymize'
     */
    @Test
    public void anonymizeTest() {
        // TODO: test anonymize
    }

    /**
     * Test the property 'dpmm'
     */
    @Test
    public void dpmmTest() {
        // TODO: test dpmm
    }

    /**
     * Test the property 'heightMm'
     */
    @Test
    public void heightMmTest() {
        // TODO: test heightMm
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'preset'
     */
    @Test
    public void presetTest() {
        // TODO: test preset
    }

    /**
     * Test the property 'sharedPort'
     */
    @Test
    public void sharedPortTest() {
        // TODO: test sharedPort
    }

    /**
     * Test the property 'webhookUrl'
     */
    @Test
    public void webhookUrlTest() {
        // TODO: test webhookUrl
    }

    /**
     * Test the property 'widthMm'
     */
    @Test
    public void widthMmTest() {
        // TODO: test widthMm
    }

}
