/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RenderedLabel
 */
public class RenderedLabelTest {
    private final RenderedLabel model = new RenderedLabel();

    /**
     * Model tests for RenderedLabel
     */
    @Test
    public void testRenderedLabel() {
        // TODO: test RenderedLabel
    }

    /**
     * Test the property 'heightPx'
     */
    @Test
    public void heightPxTest() {
        // TODO: test heightPx
    }

    /**
     * Test the property 'index'
     */
    @Test
    public void indexTest() {
        // TODO: test index
    }

    /**
     * Test the property 'png'
     */
    @Test
    public void pngTest() {
        // TODO: test png
    }

    /**
     * Test the property 'widthPx'
     */
    @Test
    public void widthPxTest() {
        // TODO: test widthPx
    }

}
