/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RenderInputBody
 */
public class RenderInputBodyTest {
    private final RenderInputBody model = new RenderInputBody();

    /**
     * Model tests for RenderInputBody
     */
    @Test
    public void testRenderInputBody() {
        // TODO: test RenderInputBody
    }

    /**
     * Test the property 'dpmm'
     */
    @Test
    public void dpmmTest() {
        // TODO: test dpmm
    }

    /**
     * Test the property 'heightMm'
     */
    @Test
    public void heightMmTest() {
        // TODO: test heightMm
    }

    /**
     * Test the property 'preset'
     */
    @Test
    public void presetTest() {
        // TODO: test preset
    }

    /**
     * Test the property 'rotation'
     */
    @Test
    public void rotationTest() {
        // TODO: test rotation
    }

    /**
     * Test the property 'widthMm'
     */
    @Test
    public void widthMmTest() {
        // TODO: test widthMm
    }

    /**
     * Test the property 'zpl'
     */
    @Test
    public void zplTest() {
        // TODO: test zpl
    }

}
