/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UnicodeOutputBody
 */
public class UnicodeOutputBodyTest {
    private final UnicodeOutputBody model = new UnicodeOutputBody();

    /**
     * Model tests for UnicodeOutputBody
     */
    @Test
    public void testUnicodeOutputBody() {
        // TODO: test UnicodeOutputBody
    }

    /**
     * Test the property 'fieldsRasterized'
     */
    @Test
    public void fieldsRasterizedTest() {
        // TODO: test fieldsRasterized
    }

    /**
     * Test the property 'skipped'
     */
    @Test
    public void skippedTest() {
        // TODO: test skipped
    }

    /**
     * Test the property 'zpl'
     */
    @Test
    public void zplTest() {
        // TODO: test zpl
    }

}
