/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.api;

import io.stripyhorse.ApiException;
import io.stripyhorse.model.ComposeInputBody;
import io.stripyhorse.model.ComposeOutputBody;
import io.stripyhorse.model.ErrorModel;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComposeApi
 */
@Disabled
public class ComposeApiTest {

    private final ComposeApi api = new ComposeApi();

    /**
     * Compose ZPL from typed JSON elements
     *
     * Labels as JSON: place text, barcodes (code128/39, QR, DataMatrix), boxes, lines, circles, images and raw ZPL passthrough on a label and get back ZPL - optionally with rendered previews. {{name}} in text/data interpolates from the variables map; an unresolved variable is an error, never a blank on a real shipment. Positions are printer dots.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void composeLabelTest() throws ApiException {
        ComposeInputBody composeInputBody = null;
        ComposeOutputBody response = api.composeLabel(composeInputBody);
        // TODO: test validations
    }

}
