/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.api;

import io.stripyhorse.ApiException;
import io.stripyhorse.model.ErrorModel;
import io.stripyhorse.model.HostStatusInputBody;
import io.stripyhorse.model.HostStatusOutputBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PrintersApi
 */
@Disabled
public class PrintersApiTest {

    private final PrintersApi api = new PrintersApi();

    /**
     * Decode a Zebra ~HS host status response
     *
     * Parses the three-line ~HS answer a Zebra printer (or our virtual printer) returns on port 9100 into typed fields - paper out, pause, buffer contents, head temperature - so you never write a positional comma parser. Accepts raw bytes, cat -v style ^B/^C markers, or hand-cleaned lines. Does not count against your monthly quota.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void parseHostStatusTest() throws ApiException {
        HostStatusInputBody hostStatusInputBody = null;
        HostStatusOutputBody response = api.parseHostStatus(hostStatusInputBody);
        // TODO: test validations
    }

}
