/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.api;

import io.stripyhorse.ApiException;
import io.stripyhorse.model.ErrorModel;
import io.stripyhorse.model.PreflightInputBody;
import io.stripyhorse.model.PreflightOutputBody;
import io.stripyhorse.model.RenderInputBody;
import io.stripyhorse.model.RenderOutputBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RenderApi
 */
@Disabled
public class RenderApiTest {

    private final RenderApi api = new RenderApi();

    /**
     * Grade a label&#39;s barcodes before they ship
     *
     * Renders the ZPL and grades every barcode the way a verifier grades a printed label: round-trip decode, measured module width in printer dots, dot-grid alignment (catches rasterized barcodes), quiet zones in modules, physical X-dimension against the spec minimum, blur tolerance, and a cross-density table - plus static lint findings (structure, encoding traps, out-of-bounds fields). Grade fail means a scanner will reject it; fix it before a truck does.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void preflightLabelTest() throws ApiException {
        PreflightInputBody preflightInputBody = null;
        PreflightOutputBody response = api.preflightLabel(preflightInputBody);
        // TODO: test validations
    }

    /**
     * Render ZPL to PNG images
     *
     * Renders every label in the ZPL stream. For a raw PNG of a single label use renderZplPng.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderZplTest() throws ApiException {
        RenderInputBody renderInputBody = null;
        RenderOutputBody response = api.renderZpl(renderInputBody);
        // TODO: test validations
    }

    /**
     * Render ZPL and return the first label as a raw PNG
     *
     * curl-friendly variant: the X-Label-Count response header carries the total label count.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void renderZplPngTest() throws ApiException {
        RenderInputBody renderInputBody = null;
        String response = api.renderZplPng(renderInputBody);
        // TODO: test validations
    }

}
