/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.stripyhorse.model.Check;
import io.stripyhorse.model.DPIVerdict;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * Barcode
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-26T05:56:03.071297194Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class Barcode {
  public static final String SERIALIZED_NAME_BLUR_MARGIN_DOTS = "blurMarginDots";
  @SerializedName(SERIALIZED_NAME_BLUR_MARGIN_DOTS)
  @javax.annotation.Nonnull
  private Long blurMarginDots;

  public static final String SERIALIZED_NAME_CHECKS = "checks";
  @SerializedName(SERIALIZED_NAME_CHECKS)
  @javax.annotation.Nullable
  private List<Check> checks;

  public static final String SERIALIZED_NAME_CROSS_DPI = "crossDpi";
  @SerializedName(SERIALIZED_NAME_CROSS_DPI)
  @javax.annotation.Nullable
  private List<DPIVerdict> crossDpi;

  public static final String SERIALIZED_NAME_FORMAT = "format";
  @SerializedName(SERIALIZED_NAME_FORMAT)
  @javax.annotation.Nonnull
  private String format;

  public static final String SERIALIZED_NAME_MODULE_DOTS = "moduleDots";
  @SerializedName(SERIALIZED_NAME_MODULE_DOTS)
  @javax.annotation.Nullable
  private Double moduleDots;

  public static final String SERIALIZED_NAME_QUIET_LEFT_MODULES = "quietLeftModules";
  @SerializedName(SERIALIZED_NAME_QUIET_LEFT_MODULES)
  @javax.annotation.Nullable
  private Double quietLeftModules;

  public static final String SERIALIZED_NAME_QUIET_RIGHT_MODULES = "quietRightModules";
  @SerializedName(SERIALIZED_NAME_QUIET_RIGHT_MODULES)
  @javax.annotation.Nullable
  private Double quietRightModules;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nonnull
  private String value;

  public static final String SERIALIZED_NAME_X_DIMENSION_MM = "xDimensionMm";
  @SerializedName(SERIALIZED_NAME_X_DIMENSION_MM)
  @javax.annotation.Nullable
  private Double xDimensionMm;

  public Barcode() {
  }

  public Barcode blurMarginDots(@javax.annotation.Nonnull Long blurMarginDots) {
    this.blurMarginDots = blurMarginDots;
    return this;
  }

  /**
   * Largest blur radius the symbol survives; 0 &#x3D; no margin
   * @return blurMarginDots
   */
  @javax.annotation.Nonnull
  public Long getBlurMarginDots() {
    return blurMarginDots;
  }

  public void setBlurMarginDots(@javax.annotation.Nonnull Long blurMarginDots) {
    this.blurMarginDots = blurMarginDots;
  }


  public Barcode checks(@javax.annotation.Nullable List<Check> checks) {
    this.checks = checks;
    return this;
  }

  public Barcode addChecksItem(Check checksItem) {
    if (this.checks == null) {
      this.checks = new ArrayList<>();
    }
    this.checks.add(checksItem);
    return this;
  }

  /**
   * Get checks
   * @return checks
   */
  @javax.annotation.Nullable
  public List<Check> getChecks() {
    return checks;
  }

  public void setChecks(@javax.annotation.Nullable List<Check> checks) {
    this.checks = checks;
  }


  public Barcode crossDpi(@javax.annotation.Nullable List<DPIVerdict> crossDpi) {
    this.crossDpi = crossDpi;
    return this;
  }

  public Barcode addCrossDpiItem(DPIVerdict crossDpiItem) {
    if (this.crossDpi == null) {
      this.crossDpi = new ArrayList<>();
    }
    this.crossDpi.add(crossDpiItem);
    return this;
  }

  /**
   * X-dimension at other print densities, same dot counts
   * @return crossDpi
   */
  @javax.annotation.Nullable
  public List<DPIVerdict> getCrossDpi() {
    return crossDpi;
  }

  public void setCrossDpi(@javax.annotation.Nullable List<DPIVerdict> crossDpi) {
    this.crossDpi = crossDpi;
  }


  public Barcode format(@javax.annotation.Nonnull String format) {
    this.format = format;
    return this;
  }

  /**
   * CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX
   * @return format
   */
  @javax.annotation.Nonnull
  public String getFormat() {
    return format;
  }

  public void setFormat(@javax.annotation.Nonnull String format) {
    this.format = format;
  }


  public Barcode moduleDots(@javax.annotation.Nullable Double moduleDots) {
    this.moduleDots = moduleDots;
    return this;
  }

  /**
   * Measured narrow-element width in printer dots (1D only)
   * @return moduleDots
   */
  @javax.annotation.Nullable
  public Double getModuleDots() {
    return moduleDots;
  }

  public void setModuleDots(@javax.annotation.Nullable Double moduleDots) {
    this.moduleDots = moduleDots;
  }


  public Barcode quietLeftModules(@javax.annotation.Nullable Double quietLeftModules) {
    this.quietLeftModules = quietLeftModules;
    return this;
  }

  /**
   * Get quietLeftModules
   * @return quietLeftModules
   */
  @javax.annotation.Nullable
  public Double getQuietLeftModules() {
    return quietLeftModules;
  }

  public void setQuietLeftModules(@javax.annotation.Nullable Double quietLeftModules) {
    this.quietLeftModules = quietLeftModules;
  }


  public Barcode quietRightModules(@javax.annotation.Nullable Double quietRightModules) {
    this.quietRightModules = quietRightModules;
    return this;
  }

  /**
   * Get quietRightModules
   * @return quietRightModules
   */
  @javax.annotation.Nullable
  public Double getQuietRightModules() {
    return quietRightModules;
  }

  public void setQuietRightModules(@javax.annotation.Nullable Double quietRightModules) {
    this.quietRightModules = quietRightModules;
  }


  public Barcode value(@javax.annotation.Nonnull String value) {
    this.value = value;
    return this;
  }

  /**
   * Get value
   * @return value
   */
  @javax.annotation.Nonnull
  public String getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nonnull String value) {
    this.value = value;
  }


  public Barcode xDimensionMm(@javax.annotation.Nullable Double xDimensionMm) {
    this.xDimensionMm = xDimensionMm;
    return this;
  }

  /**
   * Physical narrow-element width at the analyzed density
   * @return xDimensionMm
   */
  @javax.annotation.Nullable
  public Double getxDimensionMm() {
    return xDimensionMm;
  }

  public void setxDimensionMm(@javax.annotation.Nullable Double xDimensionMm) {
    this.xDimensionMm = xDimensionMm;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Barcode barcode = (Barcode) o;
    return Objects.equals(this.blurMarginDots, barcode.blurMarginDots) &&
        Objects.equals(this.checks, barcode.checks) &&
        Objects.equals(this.crossDpi, barcode.crossDpi) &&
        Objects.equals(this.format, barcode.format) &&
        Objects.equals(this.moduleDots, barcode.moduleDots) &&
        Objects.equals(this.quietLeftModules, barcode.quietLeftModules) &&
        Objects.equals(this.quietRightModules, barcode.quietRightModules) &&
        Objects.equals(this.value, barcode.value) &&
        Objects.equals(this.xDimensionMm, barcode.xDimensionMm);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(blurMarginDots, checks, crossDpi, format, moduleDots, quietLeftModules, quietRightModules, value, xDimensionMm);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Barcode {\n");
    sb.append("    blurMarginDots: ").append(toIndentedString(blurMarginDots)).append("\n");
    sb.append("    checks: ").append(toIndentedString(checks)).append("\n");
    sb.append("    crossDpi: ").append(toIndentedString(crossDpi)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    moduleDots: ").append(toIndentedString(moduleDots)).append("\n");
    sb.append("    quietLeftModules: ").append(toIndentedString(quietLeftModules)).append("\n");
    sb.append("    quietRightModules: ").append(toIndentedString(quietRightModules)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    xDimensionMm: ").append(toIndentedString(xDimensionMm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("blurMarginDots", "checks", "crossDpi", "format", "moduleDots", "quietLeftModules", "quietRightModules", "value", "xDimensionMm"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("blurMarginDots", "checks", "format", "value"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Barcode
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Barcode.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Barcode is not found in the empty JSON string", Barcode.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Barcode.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Barcode` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Barcode.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("checks") != null && !jsonObj.get("checks").isJsonNull()) {
        if (!jsonObj.get("checks").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `checks` to be an array in the JSON string but got `%s`", jsonObj.get("checks").toString()));
        }
        JsonArray jsonArraychecks = jsonObj.getAsJsonArray("checks");
        // validate the required field `checks` (array)
        for (int i = 0; i < jsonArraychecks.size(); i++) {
          Check.validateJsonElement(jsonArraychecks.get(i));
        }
      }
      if (jsonObj.get("crossDpi") != null && !jsonObj.get("crossDpi").isJsonNull()) {
        JsonArray jsonArraycrossDpi = jsonObj.getAsJsonArray("crossDpi");
        if (jsonArraycrossDpi != null) {
          // ensure the json data is an array
          if (!jsonObj.get("crossDpi").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `crossDpi` to be an array in the JSON string but got `%s`", jsonObj.get("crossDpi").toString()));
          }

          // validate the optional field `crossDpi` (array)
          for (int i = 0; i < jsonArraycrossDpi.size(); i++) {
            DPIVerdict.validateJsonElement(jsonArraycrossDpi.get(i));
          };
        }
      }
      if (!jsonObj.get("format").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `format` to be a primitive type in the JSON string but got `%s`", jsonObj.get("format").toString()));
      }
      if (!jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Barcode.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Barcode' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Barcode> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Barcode.class));

       return (TypeAdapter<T>) new TypeAdapter<Barcode>() {
           @Override
           public void write(JsonWriter out, Barcode value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Barcode read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Barcode given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Barcode
   * @throws IOException if the JSON string is invalid with respect to Barcode
   */
  public static Barcode fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Barcode.class);
  }

  /**
   * Convert an instance of Barcode to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

