/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * CreatePrinterInputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-25T17:41:37.765707888Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class CreatePrinterInputBody {
  /**
   * Print density in dots/mm (152/203/300/600 dpi); default 8
   */
  @JsonAdapter(DpmmEnum.Adapter.class)
  public enum DpmmEnum {
    NUMBER_6(6l),
    
    NUMBER_8(8l),
    
    NUMBER_12(12l),
    
    NUMBER_24(24l);

    private Long value;

    DpmmEnum(Long value) {
      this.value = value;
    }

    public Long getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DpmmEnum fromValue(Long value) {
      for (DpmmEnum b : DpmmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DpmmEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DpmmEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DpmmEnum read(final JsonReader jsonReader) throws IOException {
        Long value =  jsonReader.nextLong();
        return DpmmEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Long value = jsonElement.getAsLong();
      DpmmEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DPMM = "dpmm";
  @SerializedName(SERIALIZED_NAME_DPMM)
  @javax.annotation.Nullable
  private DpmmEnum dpmm;

  public static final String SERIALIZED_NAME_HEIGHT_MM = "heightMm";
  @SerializedName(SERIALIZED_NAME_HEIGHT_MM)
  @javax.annotation.Nullable
  private Double heightMm;

  /**
   * Gets or Sets mode
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    EMPTY(""),
    
    EPHEMERAL("ephemeral"),
    
    PERSISTENT("persistent");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nullable
  private ModeEnum mode;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  /**
   * Named label size in inches; alternative to widthMm/heightMm
   */
  @JsonAdapter(PresetEnum.Adapter.class)
  public enum PresetEnum {
    _4X6("4x6"),
    
    _6X4("6x4"),
    
    _4X4("4x4"),
    
    _4X2("4x2"),
    
    _2X4("2x4"),
    
    _3X5("3x5"),
    
    _5X3("5x3"),
    
    _2X3("2x3"),
    
    _3X2("3x2"),
    
    NETSTAMP("netstamp"),
    
    _2_25X1_25("2.25x1.25"),
    
    _2X1("2x1"),
    
    _3X1("3x1"),
    
    _4X1("4x1"),
    
    _1X1("1x1"),
    
    _4X3("4x3"),
    
    _4X8("4x8"),
    
    A6("a6");

    private String value;

    PresetEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PresetEnum fromValue(String value) {
      for (PresetEnum b : PresetEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PresetEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PresetEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PresetEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PresetEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PresetEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRESET = "preset";
  @SerializedName(SERIALIZED_NAME_PRESET)
  @javax.annotation.Nullable
  private PresetEnum preset;

  public static final String SERIALIZED_NAME_WEBHOOK_URL = "webhookUrl";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_URL)
  @javax.annotation.Nullable
  private String webhookUrl;

  public static final String SERIALIZED_NAME_WIDTH_MM = "widthMm";
  @SerializedName(SERIALIZED_NAME_WIDTH_MM)
  @javax.annotation.Nullable
  private Double widthMm;

  public CreatePrinterInputBody() {
  }

  public CreatePrinterInputBody dpmm(@javax.annotation.Nullable DpmmEnum dpmm) {
    this.dpmm = dpmm;
    return this;
  }

  /**
   * Print density in dots/mm (152/203/300/600 dpi); default 8
   * @return dpmm
   */
  @javax.annotation.Nullable
  public DpmmEnum getDpmm() {
    return dpmm;
  }

  public void setDpmm(@javax.annotation.Nullable DpmmEnum dpmm) {
    this.dpmm = dpmm;
  }


  public CreatePrinterInputBody heightMm(@javax.annotation.Nullable Double heightMm) {
    this.heightMm = heightMm;
    return this;
  }

  /**
   * Get heightMm
   * minimum: 0
   * @return heightMm
   */
  @javax.annotation.Nullable
  public Double getHeightMm() {
    return heightMm;
  }

  public void setHeightMm(@javax.annotation.Nullable Double heightMm) {
    this.heightMm = heightMm;
  }


  public CreatePrinterInputBody mode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @javax.annotation.Nullable
  public ModeEnum getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nullable ModeEnum mode) {
    this.mode = mode;
  }


  public CreatePrinterInputBody name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreatePrinterInputBody preset(@javax.annotation.Nullable PresetEnum preset) {
    this.preset = preset;
    return this;
  }

  /**
   * Named label size in inches; alternative to widthMm/heightMm
   * @return preset
   */
  @javax.annotation.Nullable
  public PresetEnum getPreset() {
    return preset;
  }

  public void setPreset(@javax.annotation.Nullable PresetEnum preset) {
    this.preset = preset;
  }


  public CreatePrinterInputBody webhookUrl(@javax.annotation.Nullable String webhookUrl) {
    this.webhookUrl = webhookUrl;
    return this;
  }

  /**
   * Get webhookUrl
   * @return webhookUrl
   */
  @javax.annotation.Nullable
  public String getWebhookUrl() {
    return webhookUrl;
  }

  public void setWebhookUrl(@javax.annotation.Nullable String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }


  public CreatePrinterInputBody widthMm(@javax.annotation.Nullable Double widthMm) {
    this.widthMm = widthMm;
    return this;
  }

  /**
   * Get widthMm
   * minimum: 0
   * @return widthMm
   */
  @javax.annotation.Nullable
  public Double getWidthMm() {
    return widthMm;
  }

  public void setWidthMm(@javax.annotation.Nullable Double widthMm) {
    this.widthMm = widthMm;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePrinterInputBody createPrinterInputBody = (CreatePrinterInputBody) o;
    return Objects.equals(this.dpmm, createPrinterInputBody.dpmm) &&
        Objects.equals(this.heightMm, createPrinterInputBody.heightMm) &&
        Objects.equals(this.mode, createPrinterInputBody.mode) &&
        Objects.equals(this.name, createPrinterInputBody.name) &&
        Objects.equals(this.preset, createPrinterInputBody.preset) &&
        Objects.equals(this.webhookUrl, createPrinterInputBody.webhookUrl) &&
        Objects.equals(this.widthMm, createPrinterInputBody.widthMm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dpmm, heightMm, mode, name, preset, webhookUrl, widthMm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePrinterInputBody {\n");
    sb.append("    dpmm: ").append(toIndentedString(dpmm)).append("\n");
    sb.append("    heightMm: ").append(toIndentedString(heightMm)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    preset: ").append(toIndentedString(preset)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    widthMm: ").append(toIndentedString(widthMm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("dpmm", "heightMm", "mode", "name", "preset", "webhookUrl", "widthMm"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("name"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreatePrinterInputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreatePrinterInputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in CreatePrinterInputBody is not found in the empty JSON string", CreatePrinterInputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreatePrinterInputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `CreatePrinterInputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreatePrinterInputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `dpmm`
      if (jsonObj.get("dpmm") != null && !jsonObj.get("dpmm").isJsonNull()) {
        DpmmEnum.validateJsonElement(jsonObj.get("dpmm"));
      }
      if ((jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) && !jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      // validate the optional field `mode`
      if (jsonObj.get("mode") != null && !jsonObj.get("mode").isJsonNull()) {
        ModeEnum.validateJsonElement(jsonObj.get("mode"));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("preset") != null && !jsonObj.get("preset").isJsonNull()) && !jsonObj.get("preset").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `preset` to be a primitive type in the JSON string but got `%s`", jsonObj.get("preset").toString()));
      }
      // validate the optional field `preset`
      if (jsonObj.get("preset") != null && !jsonObj.get("preset").isJsonNull()) {
        PresetEnum.validateJsonElement(jsonObj.get("preset"));
      }
      if ((jsonObj.get("webhookUrl") != null && !jsonObj.get("webhookUrl").isJsonNull()) && !jsonObj.get("webhookUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `webhookUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("webhookUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreatePrinterInputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreatePrinterInputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreatePrinterInputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreatePrinterInputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<CreatePrinterInputBody>() {
           @Override
           public void write(JsonWriter out, CreatePrinterInputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreatePrinterInputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreatePrinterInputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreatePrinterInputBody
   * @throws IOException if the JSON string is invalid with respect to CreatePrinterInputBody
   */
  public static CreatePrinterInputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreatePrinterInputBody.class);
  }

  /**
   * Convert an instance of CreatePrinterInputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

