/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * DPIVerdict
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-28T23:29:10.609865089Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class DPIVerdict {
  public static final String SERIALIZED_NAME_DPMM = "dpmm";
  @SerializedName(SERIALIZED_NAME_DPMM)
  @javax.annotation.Nonnull
  private Long dpmm;

  public static final String SERIALIZED_NAME_OK = "ok";
  @SerializedName(SERIALIZED_NAME_OK)
  @javax.annotation.Nonnull
  private Boolean ok;

  public static final String SERIALIZED_NAME_X_DIMENSION_MM = "xDimensionMm";
  @SerializedName(SERIALIZED_NAME_X_DIMENSION_MM)
  @javax.annotation.Nonnull
  private Double xDimensionMm;

  public DPIVerdict() {
  }

  public DPIVerdict dpmm(@javax.annotation.Nonnull Long dpmm) {
    this.dpmm = dpmm;
    return this;
  }

  /**
   * Get dpmm
   * @return dpmm
   */
  @javax.annotation.Nonnull
  public Long getDpmm() {
    return dpmm;
  }

  public void setDpmm(@javax.annotation.Nonnull Long dpmm) {
    this.dpmm = dpmm;
  }


  public DPIVerdict ok(@javax.annotation.Nonnull Boolean ok) {
    this.ok = ok;
    return this;
  }

  /**
   * Get ok
   * @return ok
   */
  @javax.annotation.Nonnull
  public Boolean getOk() {
    return ok;
  }

  public void setOk(@javax.annotation.Nonnull Boolean ok) {
    this.ok = ok;
  }


  public DPIVerdict xDimensionMm(@javax.annotation.Nonnull Double xDimensionMm) {
    this.xDimensionMm = xDimensionMm;
    return this;
  }

  /**
   * Get xDimensionMm
   * @return xDimensionMm
   */
  @javax.annotation.Nonnull
  public Double getxDimensionMm() {
    return xDimensionMm;
  }

  public void setxDimensionMm(@javax.annotation.Nonnull Double xDimensionMm) {
    this.xDimensionMm = xDimensionMm;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DPIVerdict dpIVerdict = (DPIVerdict) o;
    return Objects.equals(this.dpmm, dpIVerdict.dpmm) &&
        Objects.equals(this.ok, dpIVerdict.ok) &&
        Objects.equals(this.xDimensionMm, dpIVerdict.xDimensionMm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dpmm, ok, xDimensionMm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DPIVerdict {\n");
    sb.append("    dpmm: ").append(toIndentedString(dpmm)).append("\n");
    sb.append("    ok: ").append(toIndentedString(ok)).append("\n");
    sb.append("    xDimensionMm: ").append(toIndentedString(xDimensionMm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("dpmm", "ok", "xDimensionMm"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("dpmm", "ok", "xDimensionMm"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DPIVerdict
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DPIVerdict.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in DPIVerdict is not found in the empty JSON string", DPIVerdict.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DPIVerdict.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `DPIVerdict` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DPIVerdict.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DPIVerdict.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DPIVerdict' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DPIVerdict> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DPIVerdict.class));

       return (TypeAdapter<T>) new TypeAdapter<DPIVerdict>() {
           @Override
           public void write(JsonWriter out, DPIVerdict value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DPIVerdict read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DPIVerdict given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DPIVerdict
   * @throws IOException if the JSON string is invalid with respect to DPIVerdict
   */
  public static DPIVerdict fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DPIVerdict.class);
  }

  /**
   * Convert an instance of DPIVerdict to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

