/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * Element
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-26T03:15:11.832641834Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class Element {
  /**
   * Alignment when wrapping
   */
  @JsonAdapter(AlignEnum.Adapter.class)
  public enum AlignEnum {
    EMPTY(""),
    
    LEFT("left"),
    
    CENTER("center"),
    
    RIGHT("right"),
    
    JUSTIFY("justify");

    private String value;

    AlignEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AlignEnum fromValue(String value) {
      for (AlignEnum b : AlignEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AlignEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AlignEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AlignEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AlignEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      AlignEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ALIGN = "align";
  @SerializedName(SERIALIZED_NAME_ALIGN)
  @javax.annotation.Nullable
  private AlignEnum align;

  public static final String SERIALIZED_NAME_COLUMNS = "columns";
  @SerializedName(SERIALIZED_NAME_COLUMNS)
  @javax.annotation.Nullable
  private Long columns;

  public static final String SERIALIZED_NAME_CORNER_RADIUS = "cornerRadius";
  @SerializedName(SERIALIZED_NAME_CORNER_RADIUS)
  @javax.annotation.Nullable
  private Long cornerRadius;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nullable
  private String data;

  public static final String SERIALIZED_NAME_DIAMETER = "diameter";
  @SerializedName(SERIALIZED_NAME_DIAMETER)
  @javax.annotation.Nullable
  private Long diameter;

  /**
   * QR error correction (default M)
   */
  @JsonAdapter(ErrorCorrectionEnum.Adapter.class)
  public enum ErrorCorrectionEnum {
    EMPTY(""),
    
    L("L"),
    
    M("M"),
    
    Q("Q"),
    
    H("H");

    private String value;

    ErrorCorrectionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ErrorCorrectionEnum fromValue(String value) {
      for (ErrorCorrectionEnum b : ErrorCorrectionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ErrorCorrectionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ErrorCorrectionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ErrorCorrectionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ErrorCorrectionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ErrorCorrectionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ERROR_CORRECTION = "errorCorrection";
  @SerializedName(SERIALIZED_NAME_ERROR_CORRECTION)
  @javax.annotation.Nullable
  private ErrorCorrectionEnum errorCorrection;

  public static final String SERIALIZED_NAME_FONT = "font";
  @SerializedName(SERIALIZED_NAME_FONT)
  @javax.annotation.Nullable
  private String font;

  public static final String SERIALIZED_NAME_FONT_HEIGHT = "fontHeight";
  @SerializedName(SERIALIZED_NAME_FONT_HEIGHT)
  @javax.annotation.Nullable
  private Long fontHeight;

  public static final String SERIALIZED_NAME_FONT_WIDTH = "fontWidth";
  @SerializedName(SERIALIZED_NAME_FONT_WIDTH)
  @javax.annotation.Nullable
  private Long fontWidth;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  @javax.annotation.Nullable
  private Long height;

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  @javax.annotation.Nullable
  private Long length;

  public static final String SERIALIZED_NAME_LINES = "lines";
  @SerializedName(SERIALIZED_NAME_LINES)
  @javax.annotation.Nullable
  private Long lines;

  public static final String SERIALIZED_NAME_MAGNIFICATION = "magnification";
  @SerializedName(SERIALIZED_NAME_MAGNIFICATION)
  @javax.annotation.Nullable
  private Long magnification;

  public static final String SERIALIZED_NAME_MAX_WIDTH = "maxWidth";
  @SerializedName(SERIALIZED_NAME_MAX_WIDTH)
  @javax.annotation.Nullable
  private Long maxWidth;

  public static final String SERIALIZED_NAME_MODULE_SIZE = "moduleSize";
  @SerializedName(SERIALIZED_NAME_MODULE_SIZE)
  @javax.annotation.Nullable
  private Long moduleSize;

  public static final String SERIALIZED_NAME_MODULE_WIDTH = "moduleWidth";
  @SerializedName(SERIALIZED_NAME_MODULE_WIDTH)
  @javax.annotation.Nullable
  private Long moduleWidth;

  /**
   * Line direction
   */
  @JsonAdapter(OrientationEnum.Adapter.class)
  public enum OrientationEnum {
    EMPTY(""),
    
    H("h"),
    
    V("v");

    private String value;

    OrientationEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static OrientationEnum fromValue(String value) {
      for (OrientationEnum b : OrientationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<OrientationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final OrientationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public OrientationEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return OrientationEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      OrientationEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ORIENTATION = "orientation";
  @SerializedName(SERIALIZED_NAME_ORIENTATION)
  @javax.annotation.Nullable
  private OrientationEnum orientation;

  public static final String SERIALIZED_NAME_PNG = "png";
  @SerializedName(SERIALIZED_NAME_PNG)
  @javax.annotation.Nullable
  private String png;

  public static final String SERIALIZED_NAME_PRINT_TEXT = "printText";
  @SerializedName(SERIALIZED_NAME_PRINT_TEXT)
  @javax.annotation.Nullable
  private Boolean printText;

  /**
   * Gets or Sets rotation
   */
  @JsonAdapter(RotationEnum.Adapter.class)
  public enum RotationEnum {
    NUMBER_0(0l),
    
    NUMBER_90(90l),
    
    NUMBER_180(180l),
    
    NUMBER_270(270l);

    private Long value;

    RotationEnum(Long value) {
      this.value = value;
    }

    public Long getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RotationEnum fromValue(Long value) {
      for (RotationEnum b : RotationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RotationEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RotationEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RotationEnum read(final JsonReader jsonReader) throws IOException {
        Long value =  jsonReader.nextLong();
        return RotationEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Long value = jsonElement.getAsLong();
      RotationEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_ROTATION = "rotation";
  @SerializedName(SERIALIZED_NAME_ROTATION)
  @javax.annotation.Nullable
  private RotationEnum rotation;

  public static final String SERIALIZED_NAME_ROWS = "rows";
  @SerializedName(SERIALIZED_NAME_ROWS)
  @javax.annotation.Nullable
  private Long rows;

  public static final String SERIALIZED_NAME_TEXT = "text";
  @SerializedName(SERIALIZED_NAME_TEXT)
  @javax.annotation.Nullable
  private String text;

  public static final String SERIALIZED_NAME_THICKNESS = "thickness";
  @SerializedName(SERIALIZED_NAME_THICKNESS)
  @javax.annotation.Nullable
  private Long thickness;

  public static final String SERIALIZED_NAME_THRESHOLD = "threshold";
  @SerializedName(SERIALIZED_NAME_THRESHOLD)
  @javax.annotation.Nullable
  private Long threshold;

  /**
   * What to place
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    TEXT("text"),
    
    BARCODE128("barcode128"),
    
    BARCODE39("barcode39"),
    
    QR("qr"),
    
    DATAMATRIX("datamatrix"),
    
    BOX("box"),
    
    LINE("line"),
    
    CIRCLE("circle"),
    
    GRID("grid"),
    
    IMAGE("image"),
    
    RAW("raw");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  @javax.annotation.Nullable
  private Long width;

  public static final String SERIALIZED_NAME_X = "x";
  @SerializedName(SERIALIZED_NAME_X)
  @javax.annotation.Nullable
  private Long x;

  public static final String SERIALIZED_NAME_Y = "y";
  @SerializedName(SERIALIZED_NAME_Y)
  @javax.annotation.Nullable
  private Long y;

  public static final String SERIALIZED_NAME_ZPL = "zpl";
  @SerializedName(SERIALIZED_NAME_ZPL)
  @javax.annotation.Nullable
  private String zpl;

  public Element() {
  }

  public Element align(@javax.annotation.Nullable AlignEnum align) {
    this.align = align;
    return this;
  }

  /**
   * Alignment when wrapping
   * @return align
   */
  @javax.annotation.Nullable
  public AlignEnum getAlign() {
    return align;
  }

  public void setAlign(@javax.annotation.Nullable AlignEnum align) {
    this.align = align;
  }


  public Element columns(@javax.annotation.Nullable Long columns) {
    this.columns = columns;
    return this;
  }

  /**
   * Grid columns (default 1)
   * minimum: 0
   * maximum: 50
   * @return columns
   */
  @javax.annotation.Nullable
  public Long getColumns() {
    return columns;
  }

  public void setColumns(@javax.annotation.Nullable Long columns) {
    this.columns = columns;
  }


  public Element cornerRadius(@javax.annotation.Nullable Long cornerRadius) {
    this.cornerRadius = cornerRadius;
    return this;
  }

  /**
   * Box corner rounding 0-8
   * minimum: 0
   * maximum: 8
   * @return cornerRadius
   */
  @javax.annotation.Nullable
  public Long getCornerRadius() {
    return cornerRadius;
  }

  public void setCornerRadius(@javax.annotation.Nullable Long cornerRadius) {
    this.cornerRadius = cornerRadius;
  }


  public Element data(@javax.annotation.Nullable String data) {
    this.data = data;
    return this;
  }

  /**
   * Barcode payload; {{name}} interpolates
   * @return data
   */
  @javax.annotation.Nullable
  public String getData() {
    return data;
  }

  public void setData(@javax.annotation.Nullable String data) {
    this.data = data;
  }


  public Element diameter(@javax.annotation.Nullable Long diameter) {
    this.diameter = diameter;
    return this;
  }

  /**
   * Circle diameter in dots
   * @return diameter
   */
  @javax.annotation.Nullable
  public Long getDiameter() {
    return diameter;
  }

  public void setDiameter(@javax.annotation.Nullable Long diameter) {
    this.diameter = diameter;
  }


  public Element errorCorrection(@javax.annotation.Nullable ErrorCorrectionEnum errorCorrection) {
    this.errorCorrection = errorCorrection;
    return this;
  }

  /**
   * QR error correction (default M)
   * @return errorCorrection
   */
  @javax.annotation.Nullable
  public ErrorCorrectionEnum getErrorCorrection() {
    return errorCorrection;
  }

  public void setErrorCorrection(@javax.annotation.Nullable ErrorCorrectionEnum errorCorrection) {
    this.errorCorrection = errorCorrection;
  }


  public Element font(@javax.annotation.Nullable String font) {
    this.font = font;
    return this;
  }

  /**
   * Printer font: 0 (scalable, default) or A-Z
   * @return font
   */
  @javax.annotation.Nullable
  public String getFont() {
    return font;
  }

  public void setFont(@javax.annotation.Nullable String font) {
    this.font = font;
  }


  public Element fontHeight(@javax.annotation.Nullable Long fontHeight) {
    this.fontHeight = fontHeight;
    return this;
  }

  /**
   * Character height in dots (text)
   * @return fontHeight
   */
  @javax.annotation.Nullable
  public Long getFontHeight() {
    return fontHeight;
  }

  public void setFontHeight(@javax.annotation.Nullable Long fontHeight) {
    this.fontHeight = fontHeight;
  }


  public Element fontWidth(@javax.annotation.Nullable Long fontWidth) {
    this.fontWidth = fontWidth;
    return this;
  }

  /**
   * Character width in dots; 0 follows fontHeight
   * @return fontWidth
   */
  @javax.annotation.Nullable
  public Long getFontWidth() {
    return fontWidth;
  }

  public void setFontWidth(@javax.annotation.Nullable Long fontWidth) {
    this.fontWidth = fontWidth;
  }


  public Element height(@javax.annotation.Nullable Long height) {
    this.height = height;
    return this;
  }

  /**
   * Bar height in dots (1D) / box height in dots (box)
   * @return height
   */
  @javax.annotation.Nullable
  public Long getHeight() {
    return height;
  }

  public void setHeight(@javax.annotation.Nullable Long height) {
    this.height = height;
  }


  public Element length(@javax.annotation.Nullable Long length) {
    this.length = length;
    return this;
  }

  /**
   * Line length in dots
   * @return length
   */
  @javax.annotation.Nullable
  public Long getLength() {
    return length;
  }

  public void setLength(@javax.annotation.Nullable Long length) {
    this.length = length;
  }


  public Element lines(@javax.annotation.Nullable Long lines) {
    this.lines = lines;
    return this;
  }

  /**
   * Max lines when wrapping (default 1)
   * @return lines
   */
  @javax.annotation.Nullable
  public Long getLines() {
    return lines;
  }

  public void setLines(@javax.annotation.Nullable Long lines) {
    this.lines = lines;
  }


  public Element magnification(@javax.annotation.Nullable Long magnification) {
    this.magnification = magnification;
    return this;
  }

  /**
   * QR module magnification (default 3)
   * @return magnification
   */
  @javax.annotation.Nullable
  public Long getMagnification() {
    return magnification;
  }

  public void setMagnification(@javax.annotation.Nullable Long magnification) {
    this.magnification = magnification;
  }


  public Element maxWidth(@javax.annotation.Nullable Long maxWidth) {
    this.maxWidth = maxWidth;
    return this;
  }

  /**
   * Wrap text into a block this many dots wide
   * @return maxWidth
   */
  @javax.annotation.Nullable
  public Long getMaxWidth() {
    return maxWidth;
  }

  public void setMaxWidth(@javax.annotation.Nullable Long maxWidth) {
    this.maxWidth = maxWidth;
  }


  public Element moduleSize(@javax.annotation.Nullable Long moduleSize) {
    this.moduleSize = moduleSize;
    return this;
  }

  /**
   * DataMatrix module size in dots (default 4)
   * @return moduleSize
   */
  @javax.annotation.Nullable
  public Long getModuleSize() {
    return moduleSize;
  }

  public void setModuleSize(@javax.annotation.Nullable Long moduleSize) {
    this.moduleSize = moduleSize;
  }


  public Element moduleWidth(@javax.annotation.Nullable Long moduleWidth) {
    this.moduleWidth = moduleWidth;
    return this;
  }

  /**
   * Narrow element width in dots (1D; default 3)
   * @return moduleWidth
   */
  @javax.annotation.Nullable
  public Long getModuleWidth() {
    return moduleWidth;
  }

  public void setModuleWidth(@javax.annotation.Nullable Long moduleWidth) {
    this.moduleWidth = moduleWidth;
  }


  public Element orientation(@javax.annotation.Nullable OrientationEnum orientation) {
    this.orientation = orientation;
    return this;
  }

  /**
   * Line direction
   * @return orientation
   */
  @javax.annotation.Nullable
  public OrientationEnum getOrientation() {
    return orientation;
  }

  public void setOrientation(@javax.annotation.Nullable OrientationEnum orientation) {
    this.orientation = orientation;
  }


  public Element png(@javax.annotation.Nullable String png) {
    this.png = png;
    return this;
  }

  /**
   * PNG/GIF/JPEG, base64-encoded
   * @return png
   */
  @javax.annotation.Nullable
  public String getPng() {
    return png;
  }

  public void setPng(@javax.annotation.Nullable String png) {
    this.png = png;
  }


  public Element printText(@javax.annotation.Nullable Boolean printText) {
    this.printText = printText;
    return this;
  }

  /**
   * Print the human-readable line under 1D barcodes (default true)
   * @return printText
   */
  @javax.annotation.Nullable
  public Boolean getPrintText() {
    return printText;
  }

  public void setPrintText(@javax.annotation.Nullable Boolean printText) {
    this.printText = printText;
  }


  public Element rotation(@javax.annotation.Nullable RotationEnum rotation) {
    this.rotation = rotation;
    return this;
  }

  /**
   * Get rotation
   * @return rotation
   */
  @javax.annotation.Nullable
  public RotationEnum getRotation() {
    return rotation;
  }

  public void setRotation(@javax.annotation.Nullable RotationEnum rotation) {
    this.rotation = rotation;
  }


  public Element rows(@javax.annotation.Nullable Long rows) {
    this.rows = rows;
    return this;
  }

  /**
   * Grid rows (default 1)
   * minimum: 0
   * maximum: 50
   * @return rows
   */
  @javax.annotation.Nullable
  public Long getRows() {
    return rows;
  }

  public void setRows(@javax.annotation.Nullable Long rows) {
    this.rows = rows;
  }


  public Element text(@javax.annotation.Nullable String text) {
    this.text = text;
    return this;
  }

  /**
   * Text content; {{name}} interpolates from variables
   * @return text
   */
  @javax.annotation.Nullable
  public String getText() {
    return text;
  }

  public void setText(@javax.annotation.Nullable String text) {
    this.text = text;
  }


  public Element thickness(@javax.annotation.Nullable Long thickness) {
    this.thickness = thickness;
    return this;
  }

  /**
   * Stroke thickness in dots (default 1)
   * @return thickness
   */
  @javax.annotation.Nullable
  public Long getThickness() {
    return thickness;
  }

  public void setThickness(@javax.annotation.Nullable Long thickness) {
    this.thickness = thickness;
  }


  public Element threshold(@javax.annotation.Nullable Long threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * Bitonal threshold (default 128)
   * minimum: 0
   * maximum: 255
   * @return threshold
   */
  @javax.annotation.Nullable
  public Long getThreshold() {
    return threshold;
  }

  public void setThreshold(@javax.annotation.Nullable Long threshold) {
    this.threshold = threshold;
  }


  public Element type(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * What to place
   * @return type
   */
  @javax.annotation.Nonnull
  public TypeEnum getType() {
    return type;
  }

  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public Element width(@javax.annotation.Nullable Long width) {
    this.width = width;
    return this;
  }

  /**
   * Box/image width in dots
   * @return width
   */
  @javax.annotation.Nullable
  public Long getWidth() {
    return width;
  }

  public void setWidth(@javax.annotation.Nullable Long width) {
    this.width = width;
  }


  public Element x(@javax.annotation.Nullable Long x) {
    this.x = x;
    return this;
  }

  /**
   * Left edge in dots
   * minimum: 0
   * @return x
   */
  @javax.annotation.Nullable
  public Long getX() {
    return x;
  }

  public void setX(@javax.annotation.Nullable Long x) {
    this.x = x;
  }


  public Element y(@javax.annotation.Nullable Long y) {
    this.y = y;
    return this;
  }

  /**
   * Top edge in dots
   * minimum: 0
   * @return y
   */
  @javax.annotation.Nullable
  public Long getY() {
    return y;
  }

  public void setY(@javax.annotation.Nullable Long y) {
    this.y = y;
  }


  public Element zpl(@javax.annotation.Nullable String zpl) {
    this.zpl = zpl;
    return this;
  }

  /**
   * Verbatim ZPL commands (raw only) - the escape hatch
   * @return zpl
   */
  @javax.annotation.Nullable
  public String getZpl() {
    return zpl;
  }

  public void setZpl(@javax.annotation.Nullable String zpl) {
    this.zpl = zpl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Element element = (Element) o;
    return Objects.equals(this.align, element.align) &&
        Objects.equals(this.columns, element.columns) &&
        Objects.equals(this.cornerRadius, element.cornerRadius) &&
        Objects.equals(this.data, element.data) &&
        Objects.equals(this.diameter, element.diameter) &&
        Objects.equals(this.errorCorrection, element.errorCorrection) &&
        Objects.equals(this.font, element.font) &&
        Objects.equals(this.fontHeight, element.fontHeight) &&
        Objects.equals(this.fontWidth, element.fontWidth) &&
        Objects.equals(this.height, element.height) &&
        Objects.equals(this.length, element.length) &&
        Objects.equals(this.lines, element.lines) &&
        Objects.equals(this.magnification, element.magnification) &&
        Objects.equals(this.maxWidth, element.maxWidth) &&
        Objects.equals(this.moduleSize, element.moduleSize) &&
        Objects.equals(this.moduleWidth, element.moduleWidth) &&
        Objects.equals(this.orientation, element.orientation) &&
        Objects.equals(this.png, element.png) &&
        Objects.equals(this.printText, element.printText) &&
        Objects.equals(this.rotation, element.rotation) &&
        Objects.equals(this.rows, element.rows) &&
        Objects.equals(this.text, element.text) &&
        Objects.equals(this.thickness, element.thickness) &&
        Objects.equals(this.threshold, element.threshold) &&
        Objects.equals(this.type, element.type) &&
        Objects.equals(this.width, element.width) &&
        Objects.equals(this.x, element.x) &&
        Objects.equals(this.y, element.y) &&
        Objects.equals(this.zpl, element.zpl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(align, columns, cornerRadius, data, diameter, errorCorrection, font, fontHeight, fontWidth, height, length, lines, magnification, maxWidth, moduleSize, moduleWidth, orientation, png, printText, rotation, rows, text, thickness, threshold, type, width, x, y, zpl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Element {\n");
    sb.append("    align: ").append(toIndentedString(align)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    cornerRadius: ").append(toIndentedString(cornerRadius)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    diameter: ").append(toIndentedString(diameter)).append("\n");
    sb.append("    errorCorrection: ").append(toIndentedString(errorCorrection)).append("\n");
    sb.append("    font: ").append(toIndentedString(font)).append("\n");
    sb.append("    fontHeight: ").append(toIndentedString(fontHeight)).append("\n");
    sb.append("    fontWidth: ").append(toIndentedString(fontWidth)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
    sb.append("    magnification: ").append(toIndentedString(magnification)).append("\n");
    sb.append("    maxWidth: ").append(toIndentedString(maxWidth)).append("\n");
    sb.append("    moduleSize: ").append(toIndentedString(moduleSize)).append("\n");
    sb.append("    moduleWidth: ").append(toIndentedString(moduleWidth)).append("\n");
    sb.append("    orientation: ").append(toIndentedString(orientation)).append("\n");
    sb.append("    png: ").append(toIndentedString(png)).append("\n");
    sb.append("    printText: ").append(toIndentedString(printText)).append("\n");
    sb.append("    rotation: ").append(toIndentedString(rotation)).append("\n");
    sb.append("    rows: ").append(toIndentedString(rows)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    thickness: ").append(toIndentedString(thickness)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    x: ").append(toIndentedString(x)).append("\n");
    sb.append("    y: ").append(toIndentedString(y)).append("\n");
    sb.append("    zpl: ").append(toIndentedString(zpl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("align", "columns", "cornerRadius", "data", "diameter", "errorCorrection", "font", "fontHeight", "fontWidth", "height", "length", "lines", "magnification", "maxWidth", "moduleSize", "moduleWidth", "orientation", "png", "printText", "rotation", "rows", "text", "thickness", "threshold", "type", "width", "x", "y", "zpl"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("type"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Element
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Element.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Element is not found in the empty JSON string", Element.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Element.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Element` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Element.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("align") != null && !jsonObj.get("align").isJsonNull()) && !jsonObj.get("align").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `align` to be a primitive type in the JSON string but got `%s`", jsonObj.get("align").toString()));
      }
      // validate the optional field `align`
      if (jsonObj.get("align") != null && !jsonObj.get("align").isJsonNull()) {
        AlignEnum.validateJsonElement(jsonObj.get("align"));
      }
      if ((jsonObj.get("data") != null && !jsonObj.get("data").isJsonNull()) && !jsonObj.get("data").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `data` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data").toString()));
      }
      if ((jsonObj.get("errorCorrection") != null && !jsonObj.get("errorCorrection").isJsonNull()) && !jsonObj.get("errorCorrection").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `errorCorrection` to be a primitive type in the JSON string but got `%s`", jsonObj.get("errorCorrection").toString()));
      }
      // validate the optional field `errorCorrection`
      if (jsonObj.get("errorCorrection") != null && !jsonObj.get("errorCorrection").isJsonNull()) {
        ErrorCorrectionEnum.validateJsonElement(jsonObj.get("errorCorrection"));
      }
      if ((jsonObj.get("font") != null && !jsonObj.get("font").isJsonNull()) && !jsonObj.get("font").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `font` to be a primitive type in the JSON string but got `%s`", jsonObj.get("font").toString()));
      }
      if ((jsonObj.get("orientation") != null && !jsonObj.get("orientation").isJsonNull()) && !jsonObj.get("orientation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `orientation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("orientation").toString()));
      }
      // validate the optional field `orientation`
      if (jsonObj.get("orientation") != null && !jsonObj.get("orientation").isJsonNull()) {
        OrientationEnum.validateJsonElement(jsonObj.get("orientation"));
      }
      if ((jsonObj.get("png") != null && !jsonObj.get("png").isJsonNull()) && !jsonObj.get("png").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `png` to be a primitive type in the JSON string but got `%s`", jsonObj.get("png").toString()));
      }
      // validate the optional field `rotation`
      if (jsonObj.get("rotation") != null && !jsonObj.get("rotation").isJsonNull()) {
        RotationEnum.validateJsonElement(jsonObj.get("rotation"));
      }
      if ((jsonObj.get("text") != null && !jsonObj.get("text").isJsonNull()) && !jsonObj.get("text").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `text` to be a primitive type in the JSON string but got `%s`", jsonObj.get("text").toString()));
      }
      if (!jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the required field `type`
      TypeEnum.validateJsonElement(jsonObj.get("type"));
      if ((jsonObj.get("zpl") != null && !jsonObj.get("zpl").isJsonNull()) && !jsonObj.get("zpl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `zpl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zpl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Element.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Element' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Element> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Element.class));

       return (TypeAdapter<T>) new TypeAdapter<Element>() {
           @Override
           public void write(JsonWriter out, Element value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Element read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Element given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Element
   * @throws IOException if the JSON string is invalid with respect to Element
   */
  public static Element fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Element.class);
  }

  /**
   * Convert an instance of Element to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

