/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * Faults
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-28T22:04:49.898684942Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class Faults {
  public static final String SERIALIZED_NAME_HEAD_UP = "headUp";
  @SerializedName(SERIALIZED_NAME_HEAD_UP)
  @javax.annotation.Nullable
  private Boolean headUp;

  public static final String SERIALIZED_NAME_OVER_TEMP = "overTemp";
  @SerializedName(SERIALIZED_NAME_OVER_TEMP)
  @javax.annotation.Nullable
  private Boolean overTemp;

  public static final String SERIALIZED_NAME_PAPER_OUT = "paperOut";
  @SerializedName(SERIALIZED_NAME_PAPER_OUT)
  @javax.annotation.Nullable
  private Boolean paperOut;

  public static final String SERIALIZED_NAME_PAUSED = "paused";
  @SerializedName(SERIALIZED_NAME_PAUSED)
  @javax.annotation.Nullable
  private Boolean paused;

  public static final String SERIALIZED_NAME_RIBBON_OUT = "ribbonOut";
  @SerializedName(SERIALIZED_NAME_RIBBON_OUT)
  @javax.annotation.Nullable
  private Boolean ribbonOut;

  public static final String SERIALIZED_NAME_UNDER_TEMP = "underTemp";
  @SerializedName(SERIALIZED_NAME_UNDER_TEMP)
  @javax.annotation.Nullable
  private Boolean underTemp;

  public Faults() {
  }

  public Faults headUp(@javax.annotation.Nullable Boolean headUp) {
    this.headUp = headUp;
    return this;
  }

  /**
   * Get headUp
   * @return headUp
   */
  @javax.annotation.Nullable
  public Boolean getHeadUp() {
    return headUp;
  }

  public void setHeadUp(@javax.annotation.Nullable Boolean headUp) {
    this.headUp = headUp;
  }


  public Faults overTemp(@javax.annotation.Nullable Boolean overTemp) {
    this.overTemp = overTemp;
    return this;
  }

  /**
   * Get overTemp
   * @return overTemp
   */
  @javax.annotation.Nullable
  public Boolean getOverTemp() {
    return overTemp;
  }

  public void setOverTemp(@javax.annotation.Nullable Boolean overTemp) {
    this.overTemp = overTemp;
  }


  public Faults paperOut(@javax.annotation.Nullable Boolean paperOut) {
    this.paperOut = paperOut;
    return this;
  }

  /**
   * Get paperOut
   * @return paperOut
   */
  @javax.annotation.Nullable
  public Boolean getPaperOut() {
    return paperOut;
  }

  public void setPaperOut(@javax.annotation.Nullable Boolean paperOut) {
    this.paperOut = paperOut;
  }


  public Faults paused(@javax.annotation.Nullable Boolean paused) {
    this.paused = paused;
    return this;
  }

  /**
   * Get paused
   * @return paused
   */
  @javax.annotation.Nullable
  public Boolean getPaused() {
    return paused;
  }

  public void setPaused(@javax.annotation.Nullable Boolean paused) {
    this.paused = paused;
  }


  public Faults ribbonOut(@javax.annotation.Nullable Boolean ribbonOut) {
    this.ribbonOut = ribbonOut;
    return this;
  }

  /**
   * Get ribbonOut
   * @return ribbonOut
   */
  @javax.annotation.Nullable
  public Boolean getRibbonOut() {
    return ribbonOut;
  }

  public void setRibbonOut(@javax.annotation.Nullable Boolean ribbonOut) {
    this.ribbonOut = ribbonOut;
  }


  public Faults underTemp(@javax.annotation.Nullable Boolean underTemp) {
    this.underTemp = underTemp;
    return this;
  }

  /**
   * Get underTemp
   * @return underTemp
   */
  @javax.annotation.Nullable
  public Boolean getUnderTemp() {
    return underTemp;
  }

  public void setUnderTemp(@javax.annotation.Nullable Boolean underTemp) {
    this.underTemp = underTemp;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Faults faults = (Faults) o;
    return Objects.equals(this.headUp, faults.headUp) &&
        Objects.equals(this.overTemp, faults.overTemp) &&
        Objects.equals(this.paperOut, faults.paperOut) &&
        Objects.equals(this.paused, faults.paused) &&
        Objects.equals(this.ribbonOut, faults.ribbonOut) &&
        Objects.equals(this.underTemp, faults.underTemp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(headUp, overTemp, paperOut, paused, ribbonOut, underTemp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Faults {\n");
    sb.append("    headUp: ").append(toIndentedString(headUp)).append("\n");
    sb.append("    overTemp: ").append(toIndentedString(overTemp)).append("\n");
    sb.append("    paperOut: ").append(toIndentedString(paperOut)).append("\n");
    sb.append("    paused: ").append(toIndentedString(paused)).append("\n");
    sb.append("    ribbonOut: ").append(toIndentedString(ribbonOut)).append("\n");
    sb.append("    underTemp: ").append(toIndentedString(underTemp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("headUp", "overTemp", "paperOut", "paused", "ribbonOut", "underTemp"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Faults
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Faults.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Faults is not found in the empty JSON string", Faults.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Faults.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Faults` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Faults.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Faults' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Faults> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Faults.class));

       return (TypeAdapter<T>) new TypeAdapter<Faults>() {
           @Override
           public void write(JsonWriter out, Faults value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Faults read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Faults given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Faults
   * @throws IOException if the JSON string is invalid with respect to Faults
   */
  public static Faults fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Faults.class);
  }

  /**
   * Convert an instance of Faults to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

