/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * HtmlOutputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-30T01:31:22.372154308Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class HtmlOutputBody {
  public static final String SERIALIZED_NAME_HEIGHT_PX = "heightPx";
  @SerializedName(SERIALIZED_NAME_HEIGHT_PX)
  @javax.annotation.Nonnull
  private Long heightPx;

  public static final String SERIALIZED_NAME_WIDTH_PX = "widthPx";
  @SerializedName(SERIALIZED_NAME_WIDTH_PX)
  @javax.annotation.Nonnull
  private Long widthPx;

  public static final String SERIALIZED_NAME_ZPL = "zpl";
  @SerializedName(SERIALIZED_NAME_ZPL)
  @javax.annotation.Nonnull
  private String zpl;

  public HtmlOutputBody() {
  }

  public HtmlOutputBody heightPx(@javax.annotation.Nonnull Long heightPx) {
    this.heightPx = heightPx;
    return this;
  }

  /**
   * Get heightPx
   * @return heightPx
   */
  @javax.annotation.Nonnull
  public Long getHeightPx() {
    return heightPx;
  }

  public void setHeightPx(@javax.annotation.Nonnull Long heightPx) {
    this.heightPx = heightPx;
  }


  public HtmlOutputBody widthPx(@javax.annotation.Nonnull Long widthPx) {
    this.widthPx = widthPx;
    return this;
  }

  /**
   * Get widthPx
   * @return widthPx
   */
  @javax.annotation.Nonnull
  public Long getWidthPx() {
    return widthPx;
  }

  public void setWidthPx(@javax.annotation.Nonnull Long widthPx) {
    this.widthPx = widthPx;
  }


  public HtmlOutputBody zpl(@javax.annotation.Nonnull String zpl) {
    this.zpl = zpl;
    return this;
  }

  /**
   * Get zpl
   * @return zpl
   */
  @javax.annotation.Nonnull
  public String getZpl() {
    return zpl;
  }

  public void setZpl(@javax.annotation.Nonnull String zpl) {
    this.zpl = zpl;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlOutputBody htmlOutputBody = (HtmlOutputBody) o;
    return Objects.equals(this.heightPx, htmlOutputBody.heightPx) &&
        Objects.equals(this.widthPx, htmlOutputBody.widthPx) &&
        Objects.equals(this.zpl, htmlOutputBody.zpl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heightPx, widthPx, zpl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlOutputBody {\n");
    sb.append("    heightPx: ").append(toIndentedString(heightPx)).append("\n");
    sb.append("    widthPx: ").append(toIndentedString(widthPx)).append("\n");
    sb.append("    zpl: ").append(toIndentedString(zpl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("heightPx", "widthPx", "zpl"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("heightPx", "widthPx", "zpl"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HtmlOutputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HtmlOutputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HtmlOutputBody is not found in the empty JSON string", HtmlOutputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HtmlOutputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HtmlOutputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HtmlOutputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("zpl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `zpl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("zpl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HtmlOutputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HtmlOutputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HtmlOutputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HtmlOutputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<HtmlOutputBody>() {
           @Override
           public void write(JsonWriter out, HtmlOutputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HtmlOutputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HtmlOutputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HtmlOutputBody
   * @throws IOException if the JSON string is invalid with respect to HtmlOutputBody
   */
  public static HtmlOutputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HtmlOutputBody.class);
  }

  /**
   * Convert an instance of HtmlOutputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

