/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * HtmlInputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-28T21:20:15.812398469Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class HtmlInputBody {
  /**
   * Gets or Sets compression
   */
  @JsonAdapter(CompressionEnum.Adapter.class)
  public enum CompressionEnum {
    ACS("acs"),
    
    Z64("z64");

    private String value;

    CompressionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CompressionEnum fromValue(String value) {
      for (CompressionEnum b : CompressionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CompressionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CompressionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CompressionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CompressionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      CompressionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_COMPRESSION = "compression";
  @SerializedName(SERIALIZED_NAME_COMPRESSION)
  @javax.annotation.Nullable
  private CompressionEnum compression;

  /**
   * Gets or Sets dpmm
   */
  @JsonAdapter(DpmmEnum.Adapter.class)
  public enum DpmmEnum {
    NUMBER_6(6l),
    
    NUMBER_8(8l),
    
    NUMBER_12(12l),
    
    NUMBER_24(24l);

    private Long value;

    DpmmEnum(Long value) {
      this.value = value;
    }

    public Long getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DpmmEnum fromValue(Long value) {
      for (DpmmEnum b : DpmmEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DpmmEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DpmmEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DpmmEnum read(final JsonReader jsonReader) throws IOException {
        Long value =  jsonReader.nextLong();
        return DpmmEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      Long value = jsonElement.getAsLong();
      DpmmEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DPMM = "dpmm";
  @SerializedName(SERIALIZED_NAME_DPMM)
  @javax.annotation.Nullable
  private DpmmEnum dpmm;

  public static final String SERIALIZED_NAME_HEIGHT_MM = "heightMm";
  @SerializedName(SERIALIZED_NAME_HEIGHT_MM)
  @javax.annotation.Nullable
  private Double heightMm;

  public static final String SERIALIZED_NAME_HTML = "html";
  @SerializedName(SERIALIZED_NAME_HTML)
  @javax.annotation.Nonnull
  private String html;

  /**
   * Gets or Sets preset
   */
  @JsonAdapter(PresetEnum.Adapter.class)
  public enum PresetEnum {
    _4X6("4x6"),
    
    _6X4("6x4"),
    
    _4X4("4x4"),
    
    _4X2("4x2"),
    
    _2X4("2x4"),
    
    _3X5("3x5"),
    
    _5X3("5x3"),
    
    _2X3("2x3"),
    
    _3X2("3x2"),
    
    NETSTAMP("netstamp"),
    
    _2_25X1_25("2.25x1.25"),
    
    _1_5X1("1.5x1"),
    
    _2X1("2x1"),
    
    _3X1("3x1"),
    
    _4X1("4x1"),
    
    _1X1("1x1"),
    
    _4X3("4x3"),
    
    _4X8("4x8"),
    
    A6("a6");

    private String value;

    PresetEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PresetEnum fromValue(String value) {
      for (PresetEnum b : PresetEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PresetEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PresetEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PresetEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PresetEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      PresetEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_PRESET = "preset";
  @SerializedName(SERIALIZED_NAME_PRESET)
  @javax.annotation.Nullable
  private PresetEnum preset;

  public static final String SERIALIZED_NAME_THRESHOLD = "threshold";
  @SerializedName(SERIALIZED_NAME_THRESHOLD)
  @javax.annotation.Nullable
  private Long threshold;

  public static final String SERIALIZED_NAME_WIDTH_MM = "widthMm";
  @SerializedName(SERIALIZED_NAME_WIDTH_MM)
  @javax.annotation.Nullable
  private Double widthMm;

  public HtmlInputBody() {
  }

  public HtmlInputBody compression(@javax.annotation.Nullable CompressionEnum compression) {
    this.compression = compression;
    return this;
  }

  /**
   * Get compression
   * @return compression
   */
  @javax.annotation.Nullable
  public CompressionEnum getCompression() {
    return compression;
  }

  public void setCompression(@javax.annotation.Nullable CompressionEnum compression) {
    this.compression = compression;
  }


  public HtmlInputBody dpmm(@javax.annotation.Nullable DpmmEnum dpmm) {
    this.dpmm = dpmm;
    return this;
  }

  /**
   * Get dpmm
   * @return dpmm
   */
  @javax.annotation.Nullable
  public DpmmEnum getDpmm() {
    return dpmm;
  }

  public void setDpmm(@javax.annotation.Nullable DpmmEnum dpmm) {
    this.dpmm = dpmm;
  }


  public HtmlInputBody heightMm(@javax.annotation.Nullable Double heightMm) {
    this.heightMm = heightMm;
    return this;
  }

  /**
   * Get heightMm
   * minimum: 0
   * @return heightMm
   */
  @javax.annotation.Nullable
  public Double getHeightMm() {
    return heightMm;
  }

  public void setHeightMm(@javax.annotation.Nullable Double heightMm) {
    this.heightMm = heightMm;
  }


  public HtmlInputBody html(@javax.annotation.Nonnull String html) {
    this.html = html;
    return this;
  }

  /**
   * Label markup: HTML/CSS plus &lt;zpl-barcode&gt; elements
   * @return html
   */
  @javax.annotation.Nonnull
  public String getHtml() {
    return html;
  }

  public void setHtml(@javax.annotation.Nonnull String html) {
    this.html = html;
  }


  public HtmlInputBody preset(@javax.annotation.Nullable PresetEnum preset) {
    this.preset = preset;
    return this;
  }

  /**
   * Get preset
   * @return preset
   */
  @javax.annotation.Nullable
  public PresetEnum getPreset() {
    return preset;
  }

  public void setPreset(@javax.annotation.Nullable PresetEnum preset) {
    this.preset = preset;
  }


  public HtmlInputBody threshold(@javax.annotation.Nullable Long threshold) {
    this.threshold = threshold;
    return this;
  }

  /**
   * Get threshold
   * minimum: 1
   * maximum: 255
   * @return threshold
   */
  @javax.annotation.Nullable
  public Long getThreshold() {
    return threshold;
  }

  public void setThreshold(@javax.annotation.Nullable Long threshold) {
    this.threshold = threshold;
  }


  public HtmlInputBody widthMm(@javax.annotation.Nullable Double widthMm) {
    this.widthMm = widthMm;
    return this;
  }

  /**
   * Get widthMm
   * minimum: 0
   * @return widthMm
   */
  @javax.annotation.Nullable
  public Double getWidthMm() {
    return widthMm;
  }

  public void setWidthMm(@javax.annotation.Nullable Double widthMm) {
    this.widthMm = widthMm;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlInputBody htmlInputBody = (HtmlInputBody) o;
    return Objects.equals(this.compression, htmlInputBody.compression) &&
        Objects.equals(this.dpmm, htmlInputBody.dpmm) &&
        Objects.equals(this.heightMm, htmlInputBody.heightMm) &&
        Objects.equals(this.html, htmlInputBody.html) &&
        Objects.equals(this.preset, htmlInputBody.preset) &&
        Objects.equals(this.threshold, htmlInputBody.threshold) &&
        Objects.equals(this.widthMm, htmlInputBody.widthMm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compression, dpmm, heightMm, html, preset, threshold, widthMm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlInputBody {\n");
    sb.append("    compression: ").append(toIndentedString(compression)).append("\n");
    sb.append("    dpmm: ").append(toIndentedString(dpmm)).append("\n");
    sb.append("    heightMm: ").append(toIndentedString(heightMm)).append("\n");
    sb.append("    html: ").append(toIndentedString(html)).append("\n");
    sb.append("    preset: ").append(toIndentedString(preset)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    widthMm: ").append(toIndentedString(widthMm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("compression", "dpmm", "heightMm", "html", "preset", "threshold", "widthMm"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("html"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to HtmlInputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!HtmlInputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in HtmlInputBody is not found in the empty JSON string", HtmlInputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!HtmlInputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `HtmlInputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : HtmlInputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("compression") != null && !jsonObj.get("compression").isJsonNull()) && !jsonObj.get("compression").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `compression` to be a primitive type in the JSON string but got `%s`", jsonObj.get("compression").toString()));
      }
      // validate the optional field `compression`
      if (jsonObj.get("compression") != null && !jsonObj.get("compression").isJsonNull()) {
        CompressionEnum.validateJsonElement(jsonObj.get("compression"));
      }
      // validate the optional field `dpmm`
      if (jsonObj.get("dpmm") != null && !jsonObj.get("dpmm").isJsonNull()) {
        DpmmEnum.validateJsonElement(jsonObj.get("dpmm"));
      }
      if (!jsonObj.get("html").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `html` to be a primitive type in the JSON string but got `%s`", jsonObj.get("html").toString()));
      }
      if ((jsonObj.get("preset") != null && !jsonObj.get("preset").isJsonNull()) && !jsonObj.get("preset").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `preset` to be a primitive type in the JSON string but got `%s`", jsonObj.get("preset").toString()));
      }
      // validate the optional field `preset`
      if (jsonObj.get("preset") != null && !jsonObj.get("preset").isJsonNull()) {
        PresetEnum.validateJsonElement(jsonObj.get("preset"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HtmlInputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HtmlInputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HtmlInputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HtmlInputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<HtmlInputBody>() {
           @Override
           public void write(JsonWriter out, HtmlInputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public HtmlInputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of HtmlInputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of HtmlInputBody
   * @throws IOException if the JSON string is invalid with respect to HtmlInputBody
   */
  public static HtmlInputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HtmlInputBody.class);
  }

  /**
   * Convert an instance of HtmlInputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

