/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * MediaInputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-01T04:37:53.344905678Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class MediaInputBody {
  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  @javax.annotation.Nullable
  private Long labels;

  public static final String SERIALIZED_NAME_RIBBON_METRES = "ribbonMetres";
  @SerializedName(SERIALIZED_NAME_RIBBON_METRES)
  @javax.annotation.Nullable
  private Double ribbonMetres;

  public MediaInputBody() {
  }

  public MediaInputBody labels(@javax.annotation.Nullable Long labels) {
    this.labels = labels;
    return this;
  }

  /**
   * Labels on the roll; 0 for an endless roll
   * minimum: 0
   * maximum: 1000000
   * @return labels
   */
  @javax.annotation.Nullable
  public Long getLabels() {
    return labels;
  }

  public void setLabels(@javax.annotation.Nullable Long labels) {
    this.labels = labels;
  }


  public MediaInputBody ribbonMetres(@javax.annotation.Nullable Double ribbonMetres) {
    this.ribbonMetres = ribbonMetres;
    return this;
  }

  /**
   * Ribbon on the spool in metres; 0 for endless, which is also what direct thermal looks like
   * minimum: 0
   * maximum: 10000
   * @return ribbonMetres
   */
  @javax.annotation.Nullable
  public Double getRibbonMetres() {
    return ribbonMetres;
  }

  public void setRibbonMetres(@javax.annotation.Nullable Double ribbonMetres) {
    this.ribbonMetres = ribbonMetres;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediaInputBody mediaInputBody = (MediaInputBody) o;
    return Objects.equals(this.labels, mediaInputBody.labels) &&
        Objects.equals(this.ribbonMetres, mediaInputBody.ribbonMetres);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labels, ribbonMetres);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediaInputBody {\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    ribbonMetres: ").append(toIndentedString(ribbonMetres)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("labels", "ribbonMetres"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MediaInputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MediaInputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in MediaInputBody is not found in the empty JSON string", MediaInputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MediaInputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `MediaInputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MediaInputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MediaInputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MediaInputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MediaInputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<MediaInputBody>() {
           @Override
           public void write(JsonWriter out, MediaInputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MediaInputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MediaInputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MediaInputBody
   * @throws IOException if the JSON string is invalid with respect to MediaInputBody
   */
  public static MediaInputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MediaInputBody.class);
  }

  /**
   * Convert an instance of MediaInputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

