/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.stripyhorse.model.PrinterBodyTCPStruct;
import io.stripyhorse.model.StatusSnapshot;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * PrinterBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-31T02:30:00.440569875Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class PrinterBody {
  public static final String SERIALIZED_NAME_ACCESS_MODE = "accessMode";
  @SerializedName(SERIALIZED_NAME_ACCESS_MODE)
  @javax.annotation.Nonnull
  private String accessMode;

  public static final String SERIALIZED_NAME_ANONYMIZE = "anonymize";
  @SerializedName(SERIALIZED_NAME_ANONYMIZE)
  @javax.annotation.Nonnull
  private Boolean anonymize;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DPMM = "dpmm";
  @SerializedName(SERIALIZED_NAME_DPMM)
  @javax.annotation.Nonnull
  private Long dpmm;

  public static final String SERIALIZED_NAME_EXPIRES_AT = "expiresAt";
  @SerializedName(SERIALIZED_NAME_EXPIRES_AT)
  @javax.annotation.Nullable
  private OffsetDateTime expiresAt;

  public static final String SERIALIZED_NAME_HEIGHT_MM = "heightMm";
  @SerializedName(SERIALIZED_NAME_HEIGHT_MM)
  @javax.annotation.Nonnull
  private Double heightMm;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_INGEST_URL = "ingestUrl";
  @SerializedName(SERIALIZED_NAME_INGEST_URL)
  @javax.annotation.Nullable
  private String ingestUrl;

  /**
   * Gets or Sets mode
   */
  @JsonAdapter(ModeEnum.Adapter.class)
  public enum ModeEnum {
    EPHEMERAL("ephemeral"),
    
    PERSISTENT("persistent");

    private String value;

    ModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ModeEnum fromValue(String value) {
      for (ModeEnum b : ModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ModeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ModeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MODE = "mode";
  @SerializedName(SERIALIZED_NAME_MODE)
  @javax.annotation.Nonnull
  private ModeEnum mode;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  @javax.annotation.Nullable
  private StatusSnapshot state;

  public static final String SERIALIZED_NAME_TCP = "tcp";
  @SerializedName(SERIALIZED_NAME_TCP)
  @javax.annotation.Nonnull
  private PrinterBodyTCPStruct tcp;

  public static final String SERIALIZED_NAME_WEBHOOK_SECRET = "webhookSecret";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_SECRET)
  @javax.annotation.Nullable
  private String webhookSecret;

  public static final String SERIALIZED_NAME_WEBHOOK_URL = "webhookUrl";
  @SerializedName(SERIALIZED_NAME_WEBHOOK_URL)
  @javax.annotation.Nullable
  private String webhookUrl;

  public static final String SERIALIZED_NAME_WIDTH_MM = "widthMm";
  @SerializedName(SERIALIZED_NAME_WIDTH_MM)
  @javax.annotation.Nonnull
  private Double widthMm;

  public PrinterBody() {
  }

  public PrinterBody accessMode(@javax.annotation.Nonnull String accessMode) {
    this.accessMode = accessMode;
    return this;
  }

  /**
   * Who may print to the TCP port: open (anyone), token (the stream must open with ~SH plus the ingest token), ip (only addresses the org has claimed)
   * @return accessMode
   */
  @javax.annotation.Nonnull
  public String getAccessMode() {
    return accessMode;
  }

  public void setAccessMode(@javax.annotation.Nonnull String accessMode) {
    this.accessMode = accessMode;
  }


  public PrinterBody anonymize(@javax.annotation.Nonnull Boolean anonymize) {
    this.anonymize = anonymize;
    return this;
  }

  /**
   * When true, PII is masked and graphics stripped from every captured frame
   * @return anonymize
   */
  @javax.annotation.Nonnull
  public Boolean getAnonymize() {
    return anonymize;
  }

  public void setAnonymize(@javax.annotation.Nonnull Boolean anonymize) {
    this.anonymize = anonymize;
  }


  public PrinterBody createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PrinterBody dpmm(@javax.annotation.Nonnull Long dpmm) {
    this.dpmm = dpmm;
    return this;
  }

  /**
   * Get dpmm
   * @return dpmm
   */
  @javax.annotation.Nonnull
  public Long getDpmm() {
    return dpmm;
  }

  public void setDpmm(@javax.annotation.Nonnull Long dpmm) {
    this.dpmm = dpmm;
  }


  public PrinterBody expiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getExpiresAt() {
    return expiresAt;
  }

  public void setExpiresAt(@javax.annotation.Nullable OffsetDateTime expiresAt) {
    this.expiresAt = expiresAt;
  }


  public PrinterBody heightMm(@javax.annotation.Nonnull Double heightMm) {
    this.heightMm = heightMm;
    return this;
  }

  /**
   * Get heightMm
   * @return heightMm
   */
  @javax.annotation.Nonnull
  public Double getHeightMm() {
    return heightMm;
  }

  public void setHeightMm(@javax.annotation.Nonnull Double heightMm) {
    this.heightMm = heightMm;
  }


  public PrinterBody id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public PrinterBody ingestUrl(@javax.annotation.Nullable String ingestUrl) {
    this.ingestUrl = ingestUrl;
    return this;
  }

  /**
   * HTTPS print capability URL. Only returned on creation.
   * @return ingestUrl
   */
  @javax.annotation.Nullable
  public String getIngestUrl() {
    return ingestUrl;
  }

  public void setIngestUrl(@javax.annotation.Nullable String ingestUrl) {
    this.ingestUrl = ingestUrl;
  }


  public PrinterBody mode(@javax.annotation.Nonnull ModeEnum mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @javax.annotation.Nonnull
  public ModeEnum getMode() {
    return mode;
  }

  public void setMode(@javax.annotation.Nonnull ModeEnum mode) {
    this.mode = mode;
  }


  public PrinterBody name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public PrinterBody state(@javax.annotation.Nullable StatusSnapshot state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @javax.annotation.Nullable
  public StatusSnapshot getState() {
    return state;
  }

  public void setState(@javax.annotation.Nullable StatusSnapshot state) {
    this.state = state;
  }


  public PrinterBody tcp(@javax.annotation.Nonnull PrinterBodyTCPStruct tcp) {
    this.tcp = tcp;
    return this;
  }

  /**
   * Get tcp
   * @return tcp
   */
  @javax.annotation.Nonnull
  public PrinterBodyTCPStruct getTcp() {
    return tcp;
  }

  public void setTcp(@javax.annotation.Nonnull PrinterBodyTCPStruct tcp) {
    this.tcp = tcp;
  }


  public PrinterBody webhookSecret(@javax.annotation.Nullable String webhookSecret) {
    this.webhookSecret = webhookSecret;
    return this;
  }

  /**
   * HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation.
   * @return webhookSecret
   */
  @javax.annotation.Nullable
  public String getWebhookSecret() {
    return webhookSecret;
  }

  public void setWebhookSecret(@javax.annotation.Nullable String webhookSecret) {
    this.webhookSecret = webhookSecret;
  }


  public PrinterBody webhookUrl(@javax.annotation.Nullable String webhookUrl) {
    this.webhookUrl = webhookUrl;
    return this;
  }

  /**
   * Get webhookUrl
   * @return webhookUrl
   */
  @javax.annotation.Nullable
  public String getWebhookUrl() {
    return webhookUrl;
  }

  public void setWebhookUrl(@javax.annotation.Nullable String webhookUrl) {
    this.webhookUrl = webhookUrl;
  }


  public PrinterBody widthMm(@javax.annotation.Nonnull Double widthMm) {
    this.widthMm = widthMm;
    return this;
  }

  /**
   * Get widthMm
   * @return widthMm
   */
  @javax.annotation.Nonnull
  public Double getWidthMm() {
    return widthMm;
  }

  public void setWidthMm(@javax.annotation.Nonnull Double widthMm) {
    this.widthMm = widthMm;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrinterBody printerBody = (PrinterBody) o;
    return Objects.equals(this.accessMode, printerBody.accessMode) &&
        Objects.equals(this.anonymize, printerBody.anonymize) &&
        Objects.equals(this.createdAt, printerBody.createdAt) &&
        Objects.equals(this.dpmm, printerBody.dpmm) &&
        Objects.equals(this.expiresAt, printerBody.expiresAt) &&
        Objects.equals(this.heightMm, printerBody.heightMm) &&
        Objects.equals(this.id, printerBody.id) &&
        Objects.equals(this.ingestUrl, printerBody.ingestUrl) &&
        Objects.equals(this.mode, printerBody.mode) &&
        Objects.equals(this.name, printerBody.name) &&
        Objects.equals(this.state, printerBody.state) &&
        Objects.equals(this.tcp, printerBody.tcp) &&
        Objects.equals(this.webhookSecret, printerBody.webhookSecret) &&
        Objects.equals(this.webhookUrl, printerBody.webhookUrl) &&
        Objects.equals(this.widthMm, printerBody.widthMm);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessMode, anonymize, createdAt, dpmm, expiresAt, heightMm, id, ingestUrl, mode, name, state, tcp, webhookSecret, webhookUrl, widthMm);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrinterBody {\n");
    sb.append("    accessMode: ").append(toIndentedString(accessMode)).append("\n");
    sb.append("    anonymize: ").append(toIndentedString(anonymize)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    dpmm: ").append(toIndentedString(dpmm)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("    heightMm: ").append(toIndentedString(heightMm)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ingestUrl: ").append(toIndentedString(ingestUrl)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    tcp: ").append(toIndentedString(tcp)).append("\n");
    sb.append("    webhookSecret: ").append(toIndentedString(webhookSecret)).append("\n");
    sb.append("    webhookUrl: ").append(toIndentedString(webhookUrl)).append("\n");
    sb.append("    widthMm: ").append(toIndentedString(widthMm)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("accessMode", "anonymize", "createdAt", "dpmm", "expiresAt", "heightMm", "id", "ingestUrl", "mode", "name", "state", "tcp", "webhookSecret", "webhookUrl", "widthMm"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("accessMode", "anonymize", "createdAt", "dpmm", "heightMm", "id", "mode", "name", "tcp", "widthMm"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PrinterBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PrinterBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PrinterBody is not found in the empty JSON string", PrinterBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PrinterBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PrinterBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PrinterBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("accessMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `accessMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accessMode").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("ingestUrl") != null && !jsonObj.get("ingestUrl").isJsonNull()) && !jsonObj.get("ingestUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ingestUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ingestUrl").toString()));
      }
      if (!jsonObj.get("mode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `mode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mode").toString()));
      }
      // validate the required field `mode`
      ModeEnum.validateJsonElement(jsonObj.get("mode"));
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `state`
      if (jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) {
        StatusSnapshot.validateJsonElement(jsonObj.get("state"));
      }
      // validate the required field `tcp`
      PrinterBodyTCPStruct.validateJsonElement(jsonObj.get("tcp"));
      if ((jsonObj.get("webhookSecret") != null && !jsonObj.get("webhookSecret").isJsonNull()) && !jsonObj.get("webhookSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `webhookSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("webhookSecret").toString()));
      }
      if ((jsonObj.get("webhookUrl") != null && !jsonObj.get("webhookUrl").isJsonNull()) && !jsonObj.get("webhookUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `webhookUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("webhookUrl").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PrinterBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PrinterBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PrinterBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PrinterBody.class));

       return (TypeAdapter<T>) new TypeAdapter<PrinterBody>() {
           @Override
           public void write(JsonWriter out, PrinterBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PrinterBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PrinterBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PrinterBody
   * @throws IOException if the JSON string is invalid with respect to PrinterBody
   */
  public static PrinterBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PrinterBody.class);
  }

  /**
   * Convert an instance of PrinterBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

