/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * RenderedLabel
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-29T23:14:08.633770422Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class RenderedLabel {
  public static final String SERIALIZED_NAME_HEIGHT_PX = "heightPx";
  @SerializedName(SERIALIZED_NAME_HEIGHT_PX)
  @javax.annotation.Nonnull
  private Long heightPx;

  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  @javax.annotation.Nonnull
  private Long index;

  public static final String SERIALIZED_NAME_PNG = "png";
  @SerializedName(SERIALIZED_NAME_PNG)
  @javax.annotation.Nonnull
  private String png;

  public static final String SERIALIZED_NAME_WIDTH_PX = "widthPx";
  @SerializedName(SERIALIZED_NAME_WIDTH_PX)
  @javax.annotation.Nonnull
  private Long widthPx;

  public RenderedLabel() {
  }

  public RenderedLabel heightPx(@javax.annotation.Nonnull Long heightPx) {
    this.heightPx = heightPx;
    return this;
  }

  /**
   * Get heightPx
   * @return heightPx
   */
  @javax.annotation.Nonnull
  public Long getHeightPx() {
    return heightPx;
  }

  public void setHeightPx(@javax.annotation.Nonnull Long heightPx) {
    this.heightPx = heightPx;
  }


  public RenderedLabel index(@javax.annotation.Nonnull Long index) {
    this.index = index;
    return this;
  }

  /**
   * Get index
   * @return index
   */
  @javax.annotation.Nonnull
  public Long getIndex() {
    return index;
  }

  public void setIndex(@javax.annotation.Nonnull Long index) {
    this.index = index;
  }


  public RenderedLabel png(@javax.annotation.Nonnull String png) {
    this.png = png;
    return this;
  }

  /**
   * Base64-encoded PNG
   * @return png
   */
  @javax.annotation.Nonnull
  public String getPng() {
    return png;
  }

  public void setPng(@javax.annotation.Nonnull String png) {
    this.png = png;
  }


  public RenderedLabel widthPx(@javax.annotation.Nonnull Long widthPx) {
    this.widthPx = widthPx;
    return this;
  }

  /**
   * Get widthPx
   * @return widthPx
   */
  @javax.annotation.Nonnull
  public Long getWidthPx() {
    return widthPx;
  }

  public void setWidthPx(@javax.annotation.Nonnull Long widthPx) {
    this.widthPx = widthPx;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RenderedLabel renderedLabel = (RenderedLabel) o;
    return Objects.equals(this.heightPx, renderedLabel.heightPx) &&
        Objects.equals(this.index, renderedLabel.index) &&
        Objects.equals(this.png, renderedLabel.png) &&
        Objects.equals(this.widthPx, renderedLabel.widthPx);
  }

  @Override
  public int hashCode() {
    return Objects.hash(heightPx, index, png, widthPx);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RenderedLabel {\n");
    sb.append("    heightPx: ").append(toIndentedString(heightPx)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    png: ").append(toIndentedString(png)).append("\n");
    sb.append("    widthPx: ").append(toIndentedString(widthPx)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("heightPx", "index", "png", "widthPx"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("heightPx", "index", "png", "widthPx"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RenderedLabel
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RenderedLabel.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RenderedLabel is not found in the empty JSON string", RenderedLabel.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RenderedLabel.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RenderedLabel` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RenderedLabel.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("png").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `png` to be a primitive type in the JSON string but got `%s`", jsonObj.get("png").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RenderedLabel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RenderedLabel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RenderedLabel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RenderedLabel.class));

       return (TypeAdapter<T>) new TypeAdapter<RenderedLabel>() {
           @Override
           public void write(JsonWriter out, RenderedLabel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RenderedLabel read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RenderedLabel given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RenderedLabel
   * @throws IOException if the JSON string is invalid with respect to RenderedLabel
   */
  public static RenderedLabel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RenderedLabel.class);
  }

  /**
   * Convert an instance of RenderedLabel to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

