/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.stripyhorse.model.RenderedLabel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonNull;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * RenderOutputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-25T20:52:49.742615742Z[Etc/UTC]", comments = "Generator version: 7.26.0-SNAPSHOT")
public class RenderOutputBody {
  public static final String SERIALIZED_NAME_LABEL_COUNT = "labelCount";
  @SerializedName(SERIALIZED_NAME_LABEL_COUNT)
  @javax.annotation.Nonnull
  private Long labelCount;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  @javax.annotation.Nullable
  private List<RenderedLabel> labels;

  public RenderOutputBody() {
  }

  public RenderOutputBody labelCount(@javax.annotation.Nonnull Long labelCount) {
    this.labelCount = labelCount;
    return this;
  }

  /**
   * Get labelCount
   * @return labelCount
   */
  @javax.annotation.Nonnull
  public Long getLabelCount() {
    return labelCount;
  }

  public void setLabelCount(@javax.annotation.Nonnull Long labelCount) {
    this.labelCount = labelCount;
  }


  public RenderOutputBody labels(@javax.annotation.Nullable List<RenderedLabel> labels) {
    this.labels = labels;
    return this;
  }

  public RenderOutputBody addLabelsItem(RenderedLabel labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
   * Get labels
   * @return labels
   */
  @javax.annotation.Nullable
  public List<RenderedLabel> getLabels() {
    return labels;
  }

  public void setLabels(@javax.annotation.Nullable List<RenderedLabel> labels) {
    this.labels = labels;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RenderOutputBody renderOutputBody = (RenderOutputBody) o;
    return Objects.equals(this.labelCount, renderOutputBody.labelCount) &&
        Objects.equals(this.labels, renderOutputBody.labels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelCount, labels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RenderOutputBody {\n");
    sb.append("    labelCount: ").append(toIndentedString(labelCount)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("labelCount", "labels"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("labelCount", "labels"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RenderOutputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RenderOutputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in RenderOutputBody is not found in the empty JSON string", RenderOutputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RenderOutputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `RenderOutputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RenderOutputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("labels") != null && !jsonObj.get("labels").isJsonNull()) {
        if (!jsonObj.get("labels").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `labels` to be an array in the JSON string but got `%s`", jsonObj.get("labels").toString()));
        }
        JsonArray jsonArraylabels = jsonObj.getAsJsonArray("labels");
        // validate the required field `labels` (array)
        for (int i = 0; i < jsonArraylabels.size(); i++) {
          RenderedLabel.validateJsonElement(jsonArraylabels.get(i));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RenderOutputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RenderOutputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RenderOutputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RenderOutputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<RenderOutputBody>() {
           @Override
           public void write(JsonWriter out, RenderOutputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RenderOutputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RenderOutputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RenderOutputBody
   * @throws IOException if the JSON string is invalid with respect to RenderOutputBody
   */
  public static RenderOutputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RenderOutputBody.class);
  }

  /**
   * Convert an instance of RenderOutputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

