/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.stripyhorse.model.Faults;
import io.stripyhorse.model.HeldJob;
import io.stripyhorse.model.Supplies;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * StatusSnapshot
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-01T04:37:53.344905678Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class StatusSnapshot {
  public static final String SERIALIZED_NAME_DARKNESS = "darkness";
  @SerializedName(SERIALIZED_NAME_DARKNESS)
  @javax.annotation.Nonnull
  private String darkness;

  public static final String SERIALIZED_NAME_FAULTS = "faults";
  @SerializedName(SERIALIZED_NAME_FAULTS)
  @javax.annotation.Nonnull
  private Faults faults;

  public static final String SERIALIZED_NAME_FORMATS_IN_BUFFER = "formatsInBuffer";
  @SerializedName(SERIALIZED_NAME_FORMATS_IN_BUFFER)
  @javax.annotation.Nonnull
  private Long formatsInBuffer;

  public static final String SERIALIZED_NAME_FRIENDLY_NAME = "friendlyName";
  @SerializedName(SERIALIZED_NAME_FRIENDLY_NAME)
  @javax.annotation.Nonnull
  private String friendlyName;

  public static final String SERIALIZED_NAME_LABEL_LENGTH_DOTS = "labelLengthDots";
  @SerializedName(SERIALIZED_NAME_LABEL_LENGTH_DOTS)
  @javax.annotation.Nonnull
  private Long labelLengthDots;

  public static final String SERIALIZED_NAME_ODOMETER = "odometer";
  @SerializedName(SERIALIZED_NAME_ODOMETER)
  @javax.annotation.Nonnull
  private Long odometer;

  public static final String SERIALIZED_NAME_QUEUE = "queue";
  @SerializedName(SERIALIZED_NAME_QUEUE)
  @javax.annotation.Nullable
  private List<HeldJob> queue;

  public static final String SERIALIZED_NAME_SPEED_IPS = "speedIps";
  @SerializedName(SERIALIZED_NAME_SPEED_IPS)
  @javax.annotation.Nonnull
  private String speedIps;

  public static final String SERIALIZED_NAME_SUPPLIES = "supplies";
  @SerializedName(SERIALIZED_NAME_SUPPLIES)
  @javax.annotation.Nonnull
  private Supplies supplies;

  public static final String SERIALIZED_NAME_TEAR_OFF = "tearOff";
  @SerializedName(SERIALIZED_NAME_TEAR_OFF)
  @javax.annotation.Nonnull
  private String tearOff;

  public static final String SERIALIZED_NAME_WIDTH_DOTS = "widthDots";
  @SerializedName(SERIALIZED_NAME_WIDTH_DOTS)
  @javax.annotation.Nonnull
  private Long widthDots;

  public StatusSnapshot() {
  }

  public StatusSnapshot darkness(@javax.annotation.Nonnull String darkness) {
    this.darkness = darkness;
    return this;
  }

  /**
   * print.tone setting, e.g. 20.0
   * @return darkness
   */
  @javax.annotation.Nonnull
  public String getDarkness() {
    return darkness;
  }

  public void setDarkness(@javax.annotation.Nonnull String darkness) {
    this.darkness = darkness;
  }


  public StatusSnapshot faults(@javax.annotation.Nonnull Faults faults) {
    this.faults = faults;
    return this;
  }

  /**
   * Get faults
   * @return faults
   */
  @javax.annotation.Nonnull
  public Faults getFaults() {
    return faults;
  }

  public void setFaults(@javax.annotation.Nonnull Faults faults) {
    this.faults = faults;
  }


  public StatusSnapshot formatsInBuffer(@javax.annotation.Nonnull Long formatsInBuffer) {
    this.formatsInBuffer = formatsInBuffer;
    return this;
  }

  /**
   * Get formatsInBuffer
   * @return formatsInBuffer
   */
  @javax.annotation.Nonnull
  public Long getFormatsInBuffer() {
    return formatsInBuffer;
  }

  public void setFormatsInBuffer(@javax.annotation.Nonnull Long formatsInBuffer) {
    this.formatsInBuffer = formatsInBuffer;
  }


  public StatusSnapshot friendlyName(@javax.annotation.Nonnull String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

  /**
   * device.friendly_name override; empty means unset
   * @return friendlyName
   */
  @javax.annotation.Nonnull
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(@javax.annotation.Nonnull String friendlyName) {
    this.friendlyName = friendlyName;
  }


  public StatusSnapshot labelLengthDots(@javax.annotation.Nonnull Long labelLengthDots) {
    this.labelLengthDots = labelLengthDots;
    return this;
  }

  /**
   * Get labelLengthDots
   * @return labelLengthDots
   */
  @javax.annotation.Nonnull
  public Long getLabelLengthDots() {
    return labelLengthDots;
  }

  public void setLabelLengthDots(@javax.annotation.Nonnull Long labelLengthDots) {
    this.labelLengthDots = labelLengthDots;
  }


  public StatusSnapshot odometer(@javax.annotation.Nonnull Long odometer) {
    this.odometer = odometer;
    return this;
  }

  /**
   * Get odometer
   * @return odometer
   */
  @javax.annotation.Nonnull
  public Long getOdometer() {
    return odometer;
  }

  public void setOdometer(@javax.annotation.Nonnull Long odometer) {
    this.odometer = odometer;
  }


  public StatusSnapshot queue(@javax.annotation.Nullable List<HeldJob> queue) {
    this.queue = queue;
    return this;
  }

  public StatusSnapshot addQueueItem(HeldJob queueItem) {
    if (this.queue == null) {
      this.queue = new ArrayList<>();
    }
    this.queue.add(queueItem);
    return this;
  }

  /**
   * Get queue
   * @return queue
   */
  @javax.annotation.Nullable
  public List<HeldJob> getQueue() {
    return queue;
  }

  public void setQueue(@javax.annotation.Nullable List<HeldJob> queue) {
    this.queue = queue;
  }


  public StatusSnapshot speedIps(@javax.annotation.Nonnull String speedIps) {
    this.speedIps = speedIps;
    return this;
  }

  /**
   * media.speed setting, inches/second
   * @return speedIps
   */
  @javax.annotation.Nonnull
  public String getSpeedIps() {
    return speedIps;
  }

  public void setSpeedIps(@javax.annotation.Nonnull String speedIps) {
    this.speedIps = speedIps;
  }


  public StatusSnapshot supplies(@javax.annotation.Nonnull Supplies supplies) {
    this.supplies = supplies;
    return this;
  }

  /**
   * What is left on the roll; zero loaded means endless
   * @return supplies
   */
  @javax.annotation.Nonnull
  public Supplies getSupplies() {
    return supplies;
  }

  public void setSupplies(@javax.annotation.Nonnull Supplies supplies) {
    this.supplies = supplies;
  }


  public StatusSnapshot tearOff(@javax.annotation.Nonnull String tearOff) {
    this.tearOff = tearOff;
    return this;
  }

  /**
   * ezpl.tear_off setting, dots
   * @return tearOff
   */
  @javax.annotation.Nonnull
  public String getTearOff() {
    return tearOff;
  }

  public void setTearOff(@javax.annotation.Nonnull String tearOff) {
    this.tearOff = tearOff;
  }


  public StatusSnapshot widthDots(@javax.annotation.Nonnull Long widthDots) {
    this.widthDots = widthDots;
    return this;
  }

  /**
   * Get widthDots
   * @return widthDots
   */
  @javax.annotation.Nonnull
  public Long getWidthDots() {
    return widthDots;
  }

  public void setWidthDots(@javax.annotation.Nonnull Long widthDots) {
    this.widthDots = widthDots;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusSnapshot statusSnapshot = (StatusSnapshot) o;
    return Objects.equals(this.darkness, statusSnapshot.darkness) &&
        Objects.equals(this.faults, statusSnapshot.faults) &&
        Objects.equals(this.formatsInBuffer, statusSnapshot.formatsInBuffer) &&
        Objects.equals(this.friendlyName, statusSnapshot.friendlyName) &&
        Objects.equals(this.labelLengthDots, statusSnapshot.labelLengthDots) &&
        Objects.equals(this.odometer, statusSnapshot.odometer) &&
        Objects.equals(this.queue, statusSnapshot.queue) &&
        Objects.equals(this.speedIps, statusSnapshot.speedIps) &&
        Objects.equals(this.supplies, statusSnapshot.supplies) &&
        Objects.equals(this.tearOff, statusSnapshot.tearOff) &&
        Objects.equals(this.widthDots, statusSnapshot.widthDots);
  }

  @Override
  public int hashCode() {
    return Objects.hash(darkness, faults, formatsInBuffer, friendlyName, labelLengthDots, odometer, queue, speedIps, supplies, tearOff, widthDots);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusSnapshot {\n");
    sb.append("    darkness: ").append(toIndentedString(darkness)).append("\n");
    sb.append("    faults: ").append(toIndentedString(faults)).append("\n");
    sb.append("    formatsInBuffer: ").append(toIndentedString(formatsInBuffer)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    labelLengthDots: ").append(toIndentedString(labelLengthDots)).append("\n");
    sb.append("    odometer: ").append(toIndentedString(odometer)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    speedIps: ").append(toIndentedString(speedIps)).append("\n");
    sb.append("    supplies: ").append(toIndentedString(supplies)).append("\n");
    sb.append("    tearOff: ").append(toIndentedString(tearOff)).append("\n");
    sb.append("    widthDots: ").append(toIndentedString(widthDots)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("darkness", "faults", "formatsInBuffer", "friendlyName", "labelLengthDots", "odometer", "queue", "speedIps", "supplies", "tearOff", "widthDots"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("darkness", "faults", "formatsInBuffer", "friendlyName", "labelLengthDots", "odometer", "queue", "speedIps", "supplies", "tearOff", "widthDots"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to StatusSnapshot
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!StatusSnapshot.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in StatusSnapshot is not found in the empty JSON string", StatusSnapshot.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!StatusSnapshot.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `StatusSnapshot` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : StatusSnapshot.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("darkness").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `darkness` to be a primitive type in the JSON string but got `%s`", jsonObj.get("darkness").toString()));
      }
      // validate the required field `faults`
      Faults.validateJsonElement(jsonObj.get("faults"));
      if (!jsonObj.get("friendlyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `friendlyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("friendlyName").toString()));
      }
      if (jsonObj.get("queue") != null && !jsonObj.get("queue").isJsonNull()) {
        if (!jsonObj.get("queue").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `queue` to be an array in the JSON string but got `%s`", jsonObj.get("queue").toString()));
        }
        JsonArray jsonArrayqueue = jsonObj.getAsJsonArray("queue");
        // validate the required field `queue` (array)
        for (int i = 0; i < jsonArrayqueue.size(); i++) {
          HeldJob.validateJsonElement(jsonArrayqueue.get(i));
        }
      }
      if (!jsonObj.get("speedIps").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `speedIps` to be a primitive type in the JSON string but got `%s`", jsonObj.get("speedIps").toString()));
      }
      // validate the required field `supplies`
      Supplies.validateJsonElement(jsonObj.get("supplies"));
      if (!jsonObj.get("tearOff").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `tearOff` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tearOff").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!StatusSnapshot.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'StatusSnapshot' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<StatusSnapshot> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(StatusSnapshot.class));

       return (TypeAdapter<T>) new TypeAdapter<StatusSnapshot>() {
           @Override
           public void write(JsonWriter out, StatusSnapshot value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public StatusSnapshot read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of StatusSnapshot given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of StatusSnapshot
   * @throws IOException if the JSON string is invalid with respect to StatusSnapshot
   */
  public static StatusSnapshot fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, StatusSnapshot.class);
  }

  /**
   * Convert an instance of StatusSnapshot to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

