/*
 * Stripy Horse API
 * Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ben@stripyhorse.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.stripyhorse.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import io.stripyhorse.JSON;

/**
 * Supplies
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-01T04:37:53.344905678Z[Etc/UTC]", comments = "Generator version: 7.24.0")
public class Supplies {
  public static final String SERIALIZED_NAME_LABELS_LEFT = "labelsLeft";
  @SerializedName(SERIALIZED_NAME_LABELS_LEFT)
  @javax.annotation.Nullable
  private Long labelsLeft;

  public static final String SERIALIZED_NAME_LABELS_LOADED = "labelsLoaded";
  @SerializedName(SERIALIZED_NAME_LABELS_LOADED)
  @javax.annotation.Nullable
  private Long labelsLoaded;

  public static final String SERIALIZED_NAME_RIBBON_MM_LEFT = "ribbonMmLeft";
  @SerializedName(SERIALIZED_NAME_RIBBON_MM_LEFT)
  @javax.annotation.Nullable
  private Long ribbonMmLeft;

  public static final String SERIALIZED_NAME_RIBBON_MM_LOADED = "ribbonMmLoaded";
  @SerializedName(SERIALIZED_NAME_RIBBON_MM_LOADED)
  @javax.annotation.Nullable
  private Long ribbonMmLoaded;

  public Supplies() {
  }

  public Supplies labelsLeft(@javax.annotation.Nullable Long labelsLeft) {
    this.labelsLeft = labelsLeft;
    return this;
  }

  /**
   * Labels left on the roll
   * @return labelsLeft
   */
  @javax.annotation.Nullable
  public Long getLabelsLeft() {
    return labelsLeft;
  }

  public void setLabelsLeft(@javax.annotation.Nullable Long labelsLeft) {
    this.labelsLeft = labelsLeft;
  }


  public Supplies labelsLoaded(@javax.annotation.Nullable Long labelsLoaded) {
    this.labelsLoaded = labelsLoaded;
    return this;
  }

  /**
   * Labels the roll held when it was fitted; 0 means an endless roll
   * @return labelsLoaded
   */
  @javax.annotation.Nullable
  public Long getLabelsLoaded() {
    return labelsLoaded;
  }

  public void setLabelsLoaded(@javax.annotation.Nullable Long labelsLoaded) {
    this.labelsLoaded = labelsLoaded;
  }


  public Supplies ribbonMmLeft(@javax.annotation.Nullable Long ribbonMmLeft) {
    this.ribbonMmLeft = ribbonMmLeft;
    return this;
  }

  /**
   * Millimetres of ribbon left
   * @return ribbonMmLeft
   */
  @javax.annotation.Nullable
  public Long getRibbonMmLeft() {
    return ribbonMmLeft;
  }

  public void setRibbonMmLeft(@javax.annotation.Nullable Long ribbonMmLeft) {
    this.ribbonMmLeft = ribbonMmLeft;
  }


  public Supplies ribbonMmLoaded(@javax.annotation.Nullable Long ribbonMmLoaded) {
    this.ribbonMmLoaded = ribbonMmLoaded;
    return this;
  }

  /**
   * Millimetres of ribbon fitted; 0 means endless, which is also what direct thermal looks like
   * @return ribbonMmLoaded
   */
  @javax.annotation.Nullable
  public Long getRibbonMmLoaded() {
    return ribbonMmLoaded;
  }

  public void setRibbonMmLoaded(@javax.annotation.Nullable Long ribbonMmLoaded) {
    this.ribbonMmLoaded = ribbonMmLoaded;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Supplies supplies = (Supplies) o;
    return Objects.equals(this.labelsLeft, supplies.labelsLeft) &&
        Objects.equals(this.labelsLoaded, supplies.labelsLoaded) &&
        Objects.equals(this.ribbonMmLeft, supplies.ribbonMmLeft) &&
        Objects.equals(this.ribbonMmLoaded, supplies.ribbonMmLoaded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelsLeft, labelsLoaded, ribbonMmLeft, ribbonMmLoaded);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Supplies {\n");
    sb.append("    labelsLeft: ").append(toIndentedString(labelsLeft)).append("\n");
    sb.append("    labelsLoaded: ").append(toIndentedString(labelsLoaded)).append("\n");
    sb.append("    ribbonMmLeft: ").append(toIndentedString(ribbonMmLeft)).append("\n");
    sb.append("    ribbonMmLoaded: ").append(toIndentedString(ribbonMmLoaded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("labelsLeft", "labelsLoaded", "ribbonMmLeft", "ribbonMmLoaded"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Supplies
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Supplies.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Supplies is not found in the empty JSON string", Supplies.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Supplies.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Supplies` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Supplies.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Supplies' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Supplies> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Supplies.class));

       return (TypeAdapter<T>) new TypeAdapter<Supplies>() {
           @Override
           public void write(JsonWriter out, Supplies value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Supplies read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Supplies given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Supplies
   * @throws IOException if the JSON string is invalid with respect to Supplies
   */
  public static Supplies fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Supplies.class);
  }

  /**
   * Convert an instance of Supplies to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

